/**
 * Seed catalogue — single source of truth for local/fixture content.
 *
 * Spec §37 seed catalogue: 8 free products, plus two paid bundles ("Idea
 * Validation Pack", "Product Definition Pack") each with 9 bundle items.
 * Every product in this file is `is_placeholder: true` — real copy pending
 * business approval (spec §37's closing line, §43.3 "clearly label seed
 * content").
 *
 * JUDGEMENT CALL (documented per plan's "seed-catalogue judgment calls"):
 * "Proven–Better–New Assessment" appears both as a standalone free product
 * AND in the spec's literal Idea Validation Pack item list. Re-using the
 * same product in both places would make the bundle's "combined price"
 * calculation nonsensical (you can't sell the same free item for money as
 * part of a paid bundle without it being a different SKU). So the bundle's
 * copy is a distinct, deeper paid product with its own slug
 * (`proven-better-new-assessment-pro`) rather than a re-listing of the free
 * `proven-better-new-assessment`.
 *
 * JUDGEMENT CALL: bundle items don't need to be independently browsable —
 * they exist as real product rows (so `bundle_items` has something to
 * reference and so a future product page could be built for them) but are
 * given `status: 'unlisted'` rather than `'published'`. Unlisted products
 * are intentionally excluded from `searchCatalogue` results and the public
 * catalogue by `fixture-source.ts` while still being valid records.
 *
 * JUDGEMENT CALL (deliberate deviation from spec §37's literal "seed as
 * draft", approved in the build plan's "Decisions locked in" section): most
 * products are `status: 'published'` so the catalogue is actually
 * browsable. Exactly two are left `'draft'` and exactly one `'scheduled'`
 * (with a future `scheduled_for`) specifically so the visibility-filtering
 * logic in `fixture-source.ts` can be exercised and tested.
 *
 * No real cover/preview images exist yet (no Storage bucket, no admin
 * upload). Product/file records deliberately omit any image URL field so
 * the UI renders its designed placeholder cover state rather than a broken
 * `<img>`.
 */

import type {
  Bundle,
  BundleItem,
  Category,
  Licence,
  Product,
  ProductSummary,
  Stage,
} from "@/types/catalogue";

// ---------------------------------------------------------------------------
// Categories (spec §7.1 — 7 categories)
// ---------------------------------------------------------------------------

export const categories: Category[] = [
  {
    id: "cat-product-development",
    name: "Product development",
    slug: "product-development",
    description: "Templates for scoping, specifying and shipping a product.",
    display_order: 1,
  },
  {
    id: "cat-business-startup",
    name: "Business & startup",
    slug: "business-startup",
    description: "Templates for starting and running an early-stage business.",
    display_order: 2,
  },
  {
    id: "cat-customer-research",
    name: "Customer research",
    slug: "customer-research",
    description: "Templates for planning, running and synthesising customer research.",
    display_order: 3,
  },
  {
    id: "cat-product-strategy",
    name: "Product strategy",
    slug: "product-strategy",
    description: "Templates for evaluating ideas and setting product direction.",
    display_order: 4,
  },
  {
    id: "cat-business-planning",
    name: "Business planning",
    slug: "business-planning",
    description: "Templates for planning the commercial side of the business.",
    display_order: 5,
  },
  {
    id: "cat-go-to-market",
    name: "Go-to-market",
    slug: "go-to-market",
    description: "Templates for planning and preparing a launch.",
    display_order: 6,
  },
  {
    id: "cat-founder-management",
    name: "Founder management",
    slug: "founder-management",
    description: "Templates for reviewing progress and managing yourself as a founder.",
    display_order: 7,
  },
];

// ---------------------------------------------------------------------------
// Stages (spec §7.1 — 8 journey stages)
// ---------------------------------------------------------------------------

export const stages: Stage[] = [
  {
    id: "stage-find-a-problem",
    name: "Find a problem",
    slug: "find-a-problem",
    description: "Identify a problem worth solving before you commit to a solution.",
    display_order: 1,
  },
  {
    id: "stage-evaluate-an-idea",
    name: "Evaluate an idea",
    slug: "evaluate-an-idea",
    description: "Decide how much confidence an idea deserves before you invest in it.",
    display_order: 2,
  },
  {
    id: "stage-understand-customers",
    name: "Understand customers",
    slug: "understand-customers",
    description: "Talk to real customers and turn conversations into evidence.",
    display_order: 3,
  },
  {
    id: "stage-define-the-product",
    name: "Define the product",
    slug: "define-the-product",
    description: "Turn a validated idea into a precise, buildable product definition.",
    display_order: 4,
  },
  {
    id: "stage-test-demand",
    name: "Test demand",
    slug: "test-demand",
    description: "Find out whether people will actually pay or commit before you build.",
    display_order: 5,
  },
  {
    id: "stage-plan-the-mvp",
    name: "Plan the MVP",
    slug: "plan-the-mvp",
    description: "Scope the smallest version of the product worth building first.",
    display_order: 6,
  },
  {
    id: "stage-prepare-to-launch",
    name: "Prepare to launch",
    slug: "prepare-to-launch",
    description: "Get the product, support and go-to-market ready before release.",
    display_order: 7,
  },
  {
    id: "stage-review-and-improve",
    name: "Review and improve",
    slug: "review-and-improve",
    description: "Review progress on a regular cadence and decide what to do next.",
    display_order: 8,
  },
];

// ---------------------------------------------------------------------------
// Licences
// ---------------------------------------------------------------------------

export const licences: Licence[] = [
  {
    id: "lic-standard-personal-commercial",
    name: "Standard Personal & Commercial Use",
    slug: "standard-personal-commercial-use",
    summary:
      "Single-purchaser licence covering personal and commercial use, including client work. Redistribution or resale of the template itself is not permitted.",
    commercial_use_allowed: true,
    client_work_allowed: true,
    redistribution_allowed: false,
  },
];

const standardLicence = licences[0]!;

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function catRef(slug: string): Pick<Category, "slug" | "name"> {
  const category = categories.find((c) => c.slug === slug);
  if (!category) throw new Error(`Unknown category slug in seed data: ${slug}`);
  return { slug: category.slug, name: category.name };
}

function stageRef(slug: string): Pick<Stage, "slug" | "name"> {
  const stage = stages.find((s) => s.slug === slug);
  if (!stage) throw new Error(`Unknown stage slug in seed data: ${slug}`);
  return { slug: stage.slug, name: stage.name };
}

export function toSummary(product: Product): ProductSummary {
  const {
    id,
    product_type,
    access_type,
    status,
    name,
    slug,
    short_description,
    outcome_statement,
    completion_minutes_min,
    completion_minutes_max,
    skill_level,
    price_minor,
    compare_at_price_minor,
    currency_code,
    featured,
    published_at,
    scheduled_for,
    categories: cats,
    stages: stgs,
    formats,
    is_placeholder,
  } = product;
  return {
    id,
    product_type,
    access_type,
    status,
    name,
    slug,
    short_description,
    outcome_statement,
    completion_minutes_min,
    completion_minutes_max,
    skill_level,
    price_minor,
    compare_at_price_minor,
    currency_code,
    featured,
    published_at,
    scheduled_for,
    categories: cats,
    stages: stgs,
    formats,
    is_placeholder,
  };
}

// ---------------------------------------------------------------------------
// Free products (spec §37 — 8 free products)
// ---------------------------------------------------------------------------

const freeProducts: Product[] = [
  {
    id: "product-idea-snapshot",
    product_type: "template",
    access_type: "free",
    status: "published",
    name: "Product Idea Snapshot",
    slug: "product-idea-snapshot",
    short_description:
      "A one-page worksheet that turns a vague idea into a testable statement of who it's for, what problem it solves, and why now.",
    full_description:
      "Most ideas don't fail because they're bad — they fail because they're vague. The Product Idea Snapshot forces you to state the problem, the customer, the proposed solution and your riskiest assumption on a single page, in plain language. It's the fastest way to find out whether an idea is specific enough to test, and it's the template every other Incy Templates worksheet assumes you've already completed.",
    outcome_statement:
      "Leave with a single-page snapshot you can show a co-founder, mentor or customer in under two minutes.",
    target_audience:
      "Solo founders and early-stage teams who have an idea but haven't written it down in a form anyone else could evaluate.",
    when_to_use: "Use this in the first hour of taking an idea seriously, before you've spent time building or researching.",
    when_not_to_use:
      "Not for ideas you've already validated with real customers — move on to the Proven–Better–New Assessment instead.",
    completion_minutes_min: 15,
    completion_minutes_max: 25,
    skill_level: "beginner",
    current_version: "1.0",
    price_minor: null,
    compare_at_price_minor: null,
    currency_code: "GBP",
    featured: true,
    published_at: "2026-06-02T09:00:00Z",
    scheduled_for: null,
    categories: [catRef("product-strategy")],
    stages: [stageRef("evaluate-an-idea")],
    formats: ["markdown", "pdf"],
    is_placeholder: true,
    licence: standardLicence,
    quality_standard: {
      purpose: true,
      inputs: true,
      instructions: true,
      completedExample: true,
      thinkingPrompts: true,
      decisionOutcome: true,
      aiAgentEdition: true,
    },
    files: [
      {
        id: "product-idea-snapshot-md",
        file_role: "template",
        file_format: "markdown",
        display_name: "Product Idea Snapshot (Markdown, AI-agent-ready)",
        is_public_preview: false,
      },
      {
        id: "product-idea-snapshot-example",
        file_role: "example",
        file_format: "pdf",
        display_name: "Completed example: a subscription meal-kit idea",
        is_public_preview: true,
      },
    ],
    seo_title: "Product Idea Snapshot — free one-page template",
    seo_description:
      "A free one-page worksheet that turns a vague idea into a testable statement of the customer, problem and riskiest assumption.",
  },
  {
    id: "proven-better-new-assessment",
    product_type: "template",
    access_type: "free",
    status: "published",
    name: "Proven–Better–New Assessment",
    slug: "proven-better-new-assessment",
    short_description:
      "Classify your idea as Proven, Better or New so you know how much evidence you actually need before committing.",
    full_description:
      "The Proven–Better–New method (see /methods/proven-better-new) separates ideas that copy a working model, ideas that improve on an existing one, and ideas that introduce genuinely new behaviour. Each category carries a different risk profile and needs a different amount of validation before you commit real time or money. This worksheet walks you through the classification and hands you the evidence checklist that follows from your answer.",
    outcome_statement:
      "A clear verdict — Proven, Better or New — plus the specific evidence that verdict requires before you proceed.",
    target_audience: "Founders and product people deciding how cautiously to approach an idea.",
    when_to_use: "Use immediately after the Product Idea Snapshot, before writing a business plan or building anything.",
    when_not_to_use:
      "Not a substitute for actual customer interviews — it tells you how much evidence you need, not whether you have it yet.",
    completion_minutes_min: 20,
    completion_minutes_max: 30,
    skill_level: "beginner",
    current_version: "1.1",
    price_minor: null,
    compare_at_price_minor: null,
    currency_code: "GBP",
    featured: true,
    published_at: "2026-06-02T09:00:00Z",
    scheduled_for: null,
    categories: [catRef("product-strategy")],
    stages: [stageRef("evaluate-an-idea")],
    formats: ["markdown", "pdf"],
    is_placeholder: true,
    licence: standardLicence,
    quality_standard: {
      purpose: true,
      inputs: true,
      instructions: true,
      thinkingPrompts: true,
      evidenceFields: true,
      decisionOutcome: true,
      aiAgentEdition: true,
    },
    files: [
      {
        id: "proven-better-new-assessment-md",
        file_role: "template",
        file_format: "markdown",
        display_name: "Proven–Better–New Assessment (Markdown, AI-agent-ready)",
        is_public_preview: false,
      },
      {
        id: "proven-better-new-assessment-example",
        file_role: "example",
        file_format: "pdf",
        display_name: "Completed example: a B2B invoicing idea",
        is_public_preview: true,
      },
    ],
    seo_title: "Proven–Better–New Assessment — free idea evaluation template",
    seo_description:
      "Classify an idea as Proven, Better or New and get the evidence checklist that follows, free.",
  },
  {
    id: "problem-definition-worksheet",
    product_type: "template",
    access_type: "free",
    status: "published",
    name: "Problem Definition Worksheet",
    slug: "problem-definition-worksheet",
    short_description:
      "A structured worksheet for writing a problem statement that's specific enough to test, instead of a hunch.",
    full_description:
      "Deliberately solution-free. This worksheet asks you to name the audience, the frequency of the problem, the current cost of it going unsolved, and the evidence you already have (versus what you're assuming). Teams that skip this step tend to build solutions to problems nobody can actually describe.",
    outcome_statement:
      "A one-paragraph problem statement with a named audience, a frequency, and a cost of the problem going unsolved.",
    target_audience: "Anyone starting from 'people struggle with X' who needs to make that concrete.",
    when_to_use: "Use before you've decided on a solution — this worksheet is deliberately solution-free.",
    when_not_to_use:
      "Not useful once you've already committed to a specific product direction; use the Product Specification instead.",
    completion_minutes_min: 20,
    completion_minutes_max: 30,
    skill_level: "beginner",
    current_version: "1.0",
    price_minor: null,
    compare_at_price_minor: null,
    currency_code: "GBP",
    featured: false,
    published_at: "2026-06-05T09:00:00Z",
    scheduled_for: null,
    categories: [catRef("customer-research")],
    stages: [stageRef("find-a-problem")],
    formats: ["markdown", "pdf"],
    is_placeholder: true,
    licence: standardLicence,
    quality_standard: {
      purpose: true,
      inputs: true,
      instructions: true,
      thinkingPrompts: true,
      evidenceFields: true,
      nextStep: true,
    },
    files: [
      {
        id: "problem-definition-worksheet-md",
        file_role: "template",
        file_format: "markdown",
        display_name: "Problem Definition Worksheet (Markdown)",
        is_public_preview: false,
      },
      {
        id: "problem-definition-worksheet-example",
        file_role: "example",
        file_format: "pdf",
        display_name: "Completed example: late invoice chasing",
        is_public_preview: true,
      },
    ],
    seo_title: "Problem Definition Worksheet — free template",
    seo_description: "Write a problem statement specific enough to test, free, in about 20 minutes.",
  },
  {
    id: "existing-alternatives-review",
    product_type: "template",
    access_type: "free",
    // Deliberately left `scheduled` (see file header) to prove scheduled
    // products are hidden from public queries until scheduled_for passes.
    status: "scheduled",
    name: "Existing Alternatives Review",
    slug: "existing-alternatives-review",
    short_description:
      "A side-by-side review of how people currently solve the problem — including doing nothing — so you know what you're really competing with.",
    full_description:
      "Founders who say 'we have no competitors' usually mean 'no other venture-backed startup does exactly this.' This worksheet widens the lens: spreadsheets, manual workarounds, competitors' adjacent products, and doing nothing are all alternatives your idea has to beat. You'll come away with a comparison table and a clearer view of the switching cost customers actually face.",
    outcome_statement:
      "A comparison table of 4–6 alternatives with their strengths, weaknesses and the switching cost people face.",
    target_audience: "Founders who assume 'no direct competitors' means 'no alternatives'.",
    when_to_use: "Use once you've defined the problem, before designing a solution.",
    when_not_to_use: "Not a substitute for direct customer conversations about why they haven't switched already.",
    completion_minutes_min: 30,
    completion_minutes_max: 45,
    skill_level: "beginner",
    current_version: "1.0",
    price_minor: null,
    compare_at_price_minor: null,
    currency_code: "GBP",
    featured: false,
    published_at: null,
    scheduled_for: "2026-08-18T09:00:00Z",
    categories: [catRef("product-strategy")],
    stages: [stageRef("find-a-problem")],
    formats: ["markdown", "pdf"],
    is_placeholder: true,
    licence: standardLicence,
    quality_standard: {
      purpose: true,
      inputs: true,
      instructions: true,
      evidenceFields: true,
    },
    files: [
      {
        id: "existing-alternatives-review-md",
        file_role: "template",
        file_format: "markdown",
        display_name: "Existing Alternatives Review (Markdown)",
        is_public_preview: false,
      },
    ],
    seo_title: "Existing Alternatives Review — free template",
    seo_description: "Review the real alternatives to your idea, including doing nothing, free.",
  },
  {
    id: "customer-interview-planner",
    product_type: "template",
    access_type: "free",
    status: "published",
    name: "Customer Interview Planner",
    slug: "customer-interview-planner",
    short_description: "Plan a round of customer interviews that produce evidence instead of polite agreement.",
    full_description:
      "Includes a target-list worksheet for deciding who to talk to and why, and an interview script built to avoid leading questions — the single most common way founders accidentally confirm what they already believed. Works for five interviews or fifteen.",
    outcome_statement: "A ready-to-use interview script and a target list of who to talk to and why.",
    target_audience: "Founders about to run their first — or next — round of customer interviews.",
    when_to_use: "Use before you contact anyone; the script is built to avoid leading questions.",
    when_not_to_use: "Not for feedback on an already-shipped feature with existing paying customers.",
    completion_minutes_min: 25,
    completion_minutes_max: 40,
    skill_level: "beginner",
    current_version: "1.2",
    price_minor: null,
    compare_at_price_minor: null,
    currency_code: "GBP",
    featured: true,
    published_at: "2026-06-10T09:00:00Z",
    scheduled_for: null,
    categories: [catRef("customer-research")],
    stages: [stageRef("understand-customers")],
    formats: ["markdown", "pdf"],
    is_placeholder: true,
    licence: standardLicence,
    quality_standard: {
      purpose: true,
      inputs: true,
      instructions: true,
      thinkingPrompts: true,
      evidenceFields: true,
      nextStep: true,
      aiAgentEdition: true,
    },
    files: [
      {
        id: "customer-interview-planner-md",
        file_role: "template",
        file_format: "markdown",
        display_name: "Customer Interview Planner (Markdown, AI-agent-ready)",
        is_public_preview: false,
      },
      {
        id: "customer-interview-planner-example",
        file_role: "example",
        file_format: "pdf",
        display_name: "Completed example: interview plan for a scheduling tool",
        is_public_preview: true,
      },
    ],
    seo_title: "Customer Interview Planner — free template",
    seo_description: "Plan customer interviews that produce real evidence, free, with a ready-to-use script.",
  },
  {
    id: "assumption-and-evidence-tracker",
    product_type: "template",
    access_type: "free",
    status: "published",
    name: "Assumption and Evidence Tracker",
    slug: "assumption-and-evidence-tracker",
    short_description:
      "A running log that separates what you're assuming from what you've actually confirmed with evidence.",
    full_description:
      "A single source of truth for 'do we actually know this, or are we assuming it.' Start it the day you begin customer research and keep it updated as evidence comes in — it becomes the backbone of every proceed/revise/pause decision you make afterwards.",
    outcome_statement:
      "A prioritised list of your riskiest unconfirmed assumptions and what evidence would resolve them.",
    target_audience: "Teams who want one place to track beliefs, not just tasks.",
    when_to_use: "Start it the day you begin customer research and keep it updated throughout.",
    when_not_to_use: "Not a project-management tool — it tracks beliefs, not tasks or deadlines.",
    completion_minutes_min: 15,
    completion_minutes_max: 20,
    skill_level: "beginner",
    current_version: "1.0",
    price_minor: null,
    compare_at_price_minor: null,
    currency_code: "GBP",
    featured: false,
    published_at: "2026-06-12T09:00:00Z",
    scheduled_for: null,
    categories: [catRef("customer-research")],
    stages: [stageRef("understand-customers")],
    formats: ["markdown"],
    is_placeholder: true,
    licence: standardLicence,
    quality_standard: {
      purpose: true,
      instructions: true,
      evidenceFields: true,
      decisionOutcome: true,
      aiAgentEdition: true,
    },
    files: [
      {
        id: "assumption-and-evidence-tracker-md",
        file_role: "template",
        file_format: "markdown",
        display_name: "Assumption and Evidence Tracker (Markdown, AI-agent-ready)",
        is_public_preview: false,
      },
    ],
    seo_title: "Assumption and Evidence Tracker — free template",
    seo_description: "Separate what you're assuming from what you've confirmed with evidence, free.",
  },
  {
    id: "mvp-scope-in-one-page",
    product_type: "template",
    access_type: "free",
    status: "published",
    name: "MVP Scope in One Page",
    slug: "mvp-scope-in-one-page",
    short_description:
      "Force your MVP onto a single page: what's in, what's explicitly out, and the one question it needs to answer.",
    full_description:
      "A short, deliberately restrictive scoping template for a first release. Naming what's explicitly out is as important as naming what's in — this is the page you hold up when someone suggests 'just one more feature' before launch.",
    outcome_statement:
      "A one-page scope you can hold yourself to when the temptation to add 'just one more feature' shows up.",
    target_audience: "Founders and small product teams about to start building.",
    when_to_use: "Use once you have a validated problem and a rough solution direction.",
    when_not_to_use:
      "Not for teams past their first release — see the Product Definition Pack's fuller MVP Scope template.",
    completion_minutes_min: 20,
    completion_minutes_max: 30,
    skill_level: "beginner",
    current_version: "1.0",
    price_minor: null,
    compare_at_price_minor: null,
    currency_code: "GBP",
    featured: true,
    published_at: "2026-06-15T09:00:00Z",
    scheduled_for: null,
    categories: [catRef("product-development")],
    stages: [stageRef("plan-the-mvp")],
    formats: ["markdown", "pdf"],
    is_placeholder: true,
    licence: standardLicence,
    quality_standard: {
      purpose: true,
      instructions: true,
      decisionOutcome: true,
      nextStep: true,
      aiAgentEdition: true,
    },
    files: [
      {
        id: "mvp-scope-in-one-page-md",
        file_role: "template",
        file_format: "markdown",
        display_name: "MVP Scope in One Page (Markdown, AI-agent-ready)",
        is_public_preview: false,
      },
      {
        id: "mvp-scope-in-one-page-example",
        file_role: "example",
        file_format: "pdf",
        display_name: "Completed example: MVP scope for a booking app",
        is_public_preview: true,
      },
    ],
    seo_title: "MVP Scope in One Page — free template",
    seo_description: "Scope your MVP on a single page: what's in, what's out, free.",
  },
  {
    id: "weekly-founder-review",
    product_type: "template",
    access_type: "free",
    // Deliberately left `draft` (see file header) to prove draft products
    // are hidden from public queries.
    status: "draft",
    name: "Weekly Founder Review",
    slug: "weekly-founder-review",
    short_description: "A 15-minute weekly ritual for reviewing progress, evidence gathered, and what to do differently next week.",
    full_description:
      "A lightweight replacement for a formal retro, built for teams of one to three people. Three questions, answered in writing, every week: what did we learn, what changed as a result, and what do we do next. Still being finalised before publication.",
    outcome_statement: "A short written answer to: what did we learn, what changed, what do we do next.",
    target_audience: "Solo founders and small teams who want a lightweight replacement for a formal retro.",
    when_to_use: "Run it at the same time every week, ideally Friday afternoon or Monday morning.",
    when_not_to_use: "Not a replacement for a formal board update once you have investors.",
    completion_minutes_min: 10,
    completion_minutes_max: 15,
    skill_level: "beginner",
    current_version: "0.9",
    price_minor: null,
    compare_at_price_minor: null,
    currency_code: "GBP",
    featured: false,
    published_at: null,
    scheduled_for: null,
    categories: [catRef("founder-management")],
    stages: [stageRef("review-and-improve")],
    formats: ["markdown"],
    is_placeholder: true,
    licence: standardLicence,
    quality_standard: {
      purpose: true,
      instructions: true,
      nextStep: true,
    },
    files: [
      {
        id: "weekly-founder-review-md",
        file_role: "template",
        file_format: "markdown",
        display_name: "Weekly Founder Review (Markdown)",
        is_public_preview: false,
      },
    ],
    seo_title: "Weekly Founder Review — free template",
    seo_description: "A 15-minute weekly review ritual for solo founders and small teams, free.",
  },
];

// ---------------------------------------------------------------------------
// Idea Validation Pack — 9 bundle items (spec §37)
// ---------------------------------------------------------------------------

const ideaValidationItems: Product[] = [
  {
    id: "idea-intake",
    product_type: "template",
    access_type: "paid",
    status: "unlisted",
    name: "Idea Intake",
    slug: "idea-intake",
    short_description: "A structured intake form that captures the idea, its source, and why it's worth evaluating now.",
    full_description: "The opening step of the Idea Validation Pack: a short, structured intake that captures the idea, where it came from, and the reason it's being taken seriously right now.",
    outcome_statement: "A one-page record of the idea as it stood on day one, for later comparison.",
    target_audience: "Founders starting the Idea Validation Pack.",
    when_to_use: "Use as the first step of the pack, before any evaluation begins.",
    when_not_to_use: "Not needed if you've already completed the free Product Idea Snapshot for this idea.",
    completion_minutes_min: 10,
    completion_minutes_max: 15,
    skill_level: "beginner",
    current_version: "1.0",
    price_minor: 900,
    compare_at_price_minor: null,
    currency_code: "GBP",
    featured: false,
    published_at: "2026-06-18T09:00:00Z",
    scheduled_for: null,
    categories: [catRef("product-strategy")],
    stages: [stageRef("evaluate-an-idea")],
    formats: ["markdown"],
    is_placeholder: true,
    licence: standardLicence,
    quality_standard: { purpose: true, instructions: true },
    files: [
      { id: "idea-intake-md", file_role: "template", file_format: "markdown", display_name: "Idea Intake (Markdown)", is_public_preview: false },
    ],
    seo_title: null,
    seo_description: null,
  },
  {
    id: "founder-fit-assessment",
    product_type: "template",
    access_type: "paid",
    // Deliberately left `draft` (see file header) alongside Weekly Founder
    // Review — still being written.
    status: "draft",
    name: "Founder Fit Assessment",
    slug: "founder-fit-assessment",
    short_description: "Assess whether this idea fits your skills, resources and risk appetite before you assess whether the market wants it.",
    full_description: "A candid self-assessment of founder-idea fit: relevant skills, time and money available, and risk appetite, scored against what the idea will actually demand. Still being finalised before publication.",
    outcome_statement: "A documented answer to whether this is the right idea for you specifically to pursue.",
    target_audience: "Founders in the Idea Validation Pack deciding whether to invest further.",
    when_to_use: "Use early, alongside Idea Intake.",
    when_not_to_use: "Not a market-validation tool — it only assesses fit, not demand.",
    completion_minutes_min: 20,
    completion_minutes_max: 30,
    skill_level: "beginner",
    current_version: "0.8",
    price_minor: 900,
    compare_at_price_minor: null,
    currency_code: "GBP",
    featured: false,
    published_at: null,
    scheduled_for: null,
    categories: [catRef("product-strategy")],
    stages: [stageRef("evaluate-an-idea")],
    formats: ["markdown"],
    is_placeholder: true,
    licence: standardLicence,
    quality_standard: { purpose: true, instructions: true, thinkingPrompts: true },
    files: [
      { id: "founder-fit-assessment-md", file_role: "template", file_format: "markdown", display_name: "Founder Fit Assessment (Markdown)", is_public_preview: false },
    ],
    seo_title: null,
    seo_description: null,
  },
  {
    id: "problem-evidence-review",
    product_type: "template",
    access_type: "paid",
    status: "unlisted",
    name: "Problem Evidence Review",
    slug: "problem-evidence-review",
    short_description: "Weigh the evidence you have for the problem's existence against the evidence you're assuming.",
    full_description: "Goes further than the free Problem Definition Worksheet: sorts every piece of 'evidence' the team has cited into confirmed, anecdotal, or assumed, and flags where the case for the problem is thinner than it feels.",
    outcome_statement: "An honest evidence rating for the problem, not just a description of it.",
    target_audience: "Teams in the Idea Validation Pack who have completed a problem definition.",
    when_to_use: "Use after the Problem Definition Worksheet, before designing a solution.",
    when_not_to_use: "Not useful before a problem statement exists.",
    completion_minutes_min: 25,
    completion_minutes_max: 35,
    skill_level: "intermediate",
    current_version: "1.0",
    price_minor: 900,
    compare_at_price_minor: null,
    currency_code: "GBP",
    featured: false,
    published_at: "2026-06-18T09:00:00Z",
    scheduled_for: null,
    categories: [catRef("customer-research")],
    stages: [stageRef("find-a-problem")],
    formats: ["markdown"],
    is_placeholder: true,
    licence: standardLicence,
    quality_standard: { purpose: true, instructions: true, evidenceFields: true },
    files: [
      { id: "problem-evidence-review-md", file_role: "template", file_format: "markdown", display_name: "Problem Evidence Review (Markdown)", is_public_preview: false },
    ],
    seo_title: null,
    seo_description: null,
  },
  {
    id: "alternatives-and-competitors",
    product_type: "template",
    access_type: "paid",
    status: "unlisted",
    name: "Alternatives and Competitors",
    slug: "alternatives-and-competitors",
    short_description: "A deeper competitive-positioning map, building on the free Existing Alternatives Review.",
    full_description: "Extends the free alternatives review into a full positioning map: direct competitors, adjacent products, manual workarounds and the cost of switching, plotted against the dimensions that matter most to your customer.",
    outcome_statement: "A positioning map showing where your idea sits relative to every real alternative.",
    target_audience: "Teams in the Idea Validation Pack who want a fuller competitive picture.",
    when_to_use: "Use after the problem is defined, before you fix on a solution.",
    when_not_to_use: "Not a substitute for talking to customers about why they haven't switched.",
    completion_minutes_min: 30,
    completion_minutes_max: 45,
    skill_level: "intermediate",
    current_version: "1.0",
    price_minor: 900,
    compare_at_price_minor: null,
    currency_code: "GBP",
    featured: false,
    published_at: "2026-06-19T09:00:00Z",
    scheduled_for: null,
    categories: [catRef("product-strategy")],
    stages: [stageRef("find-a-problem")],
    formats: ["markdown"],
    is_placeholder: true,
    licence: standardLicence,
    quality_standard: { purpose: true, instructions: true, evidenceFields: true },
    files: [
      { id: "alternatives-and-competitors-md", file_role: "template", file_format: "markdown", display_name: "Alternatives and Competitors (Markdown)", is_public_preview: false },
    ],
    seo_title: null,
    seo_description: null,
  },
  {
    id: "proven-better-new-assessment-pro",
    product_type: "template",
    access_type: "paid",
    status: "unlisted",
    name: "Proven–Better–New Assessment (Pro)",
    slug: "proven-better-new-assessment-pro",
    short_description: "The full Proven–Better–New workbook with worked scoring, facilitator notes and a team-workshop edition.",
    full_description: "The paid, deeper edition of the free Proven–Better–New Assessment: adds a weighted scoring model, facilitator notes for running the assessment as a team workshop, and worked examples for all three classifications.",
    outcome_statement: "A team-facilitated Proven/Better/New verdict with a documented evidence plan.",
    target_audience: "Teams (not solo founders) working through the Idea Validation Pack together.",
    when_to_use: "Use as part of the Idea Validation Pack, in place of the free assessment, when working as a team.",
    when_not_to_use: "If you're working solo, the free Proven–Better–New Assessment is enough.",
    completion_minutes_min: 40,
    completion_minutes_max: 60,
    skill_level: "intermediate",
    current_version: "1.0",
    price_minor: 900,
    compare_at_price_minor: null,
    currency_code: "GBP",
    featured: false,
    published_at: "2026-06-19T09:00:00Z",
    scheduled_for: null,
    categories: [catRef("product-strategy")],
    stages: [stageRef("evaluate-an-idea")],
    formats: ["markdown", "pdf"],
    is_placeholder: true,
    licence: standardLicence,
    quality_standard: { purpose: true, instructions: true, thinkingPrompts: true, evidenceFields: true, facilitatorEdition: true },
    files: [
      { id: "proven-better-new-assessment-pro-md", file_role: "template", file_format: "markdown", display_name: "Proven–Better–New Assessment Pro (Markdown)", is_public_preview: false },
      { id: "proven-better-new-assessment-pro-facilitator", file_role: "facilitator_guide", file_format: "pdf", display_name: "Facilitator guide for team workshops", is_public_preview: false },
    ],
    seo_title: null,
    seo_description: null,
  },
  {
    id: "riskiest-assumptions",
    product_type: "template",
    access_type: "paid",
    status: "unlisted",
    name: "Riskiest Assumptions",
    slug: "riskiest-assumptions",
    short_description: "Rank every assumption behind your idea by impact and uncertainty, then decide which to test first.",
    full_description: "Builds directly on the free Assumption and Evidence Tracker: plots every open assumption on an impact-versus-uncertainty grid so the team can agree, with evidence rather than opinion, which one to test first.",
    outcome_statement: "A ranked shortlist of the 3–5 assumptions worth testing next.",
    target_audience: "Teams in the Idea Validation Pack with an existing assumption log.",
    when_to_use: "Use once you have at least five assumptions logged.",
    when_not_to_use: "Not useful before you've started tracking assumptions at all.",
    completion_minutes_min: 20,
    completion_minutes_max: 30,
    skill_level: "intermediate",
    current_version: "1.0",
    price_minor: 900,
    compare_at_price_minor: null,
    currency_code: "GBP",
    featured: false,
    published_at: "2026-06-20T09:00:00Z",
    scheduled_for: null,
    categories: [catRef("product-strategy")],
    stages: [stageRef("evaluate-an-idea")],
    formats: ["markdown"],
    is_placeholder: true,
    licence: standardLicence,
    quality_standard: { purpose: true, instructions: true, evidenceFields: true, decisionOutcome: true },
    files: [
      { id: "riskiest-assumptions-md", file_role: "template", file_format: "markdown", display_name: "Riskiest Assumptions (Markdown)", is_public_preview: false },
    ],
    seo_title: null,
    seo_description: null,
  },
  {
    id: "customer-interview-system",
    product_type: "template",
    access_type: "paid",
    status: "unlisted",
    name: "Customer Interview System",
    slug: "customer-interview-system",
    short_description: "A complete interview system: scheduling scripts, a question bank, and a synthesis method for turning notes into evidence.",
    full_description: "The paid, complete version of the free Customer Interview Planner: adds outreach and scheduling scripts, a larger question bank organised by what you're trying to learn, and a structured method for synthesising raw notes into findings.",
    outcome_statement: "A repeatable interview process from outreach through to written findings.",
    target_audience: "Teams in the Idea Validation Pack planning more than a handful of interviews.",
    when_to_use: "Use once you're ready to run five or more interviews.",
    when_not_to_use: "For one or two casual conversations, the free Customer Interview Planner is enough.",
    completion_minutes_min: 45,
    completion_minutes_max: 90,
    skill_level: "intermediate",
    current_version: "1.0",
    price_minor: 900,
    compare_at_price_minor: null,
    currency_code: "GBP",
    featured: false,
    published_at: "2026-06-20T09:00:00Z",
    scheduled_for: null,
    categories: [catRef("customer-research")],
    stages: [stageRef("understand-customers")],
    formats: ["markdown"],
    is_placeholder: true,
    licence: standardLicence,
    quality_standard: { purpose: true, instructions: true, evidenceFields: true, aiAgentEdition: true },
    files: [
      { id: "customer-interview-system-md", file_role: "template", file_format: "markdown", display_name: "Customer Interview System (Markdown, AI-agent-ready)", is_public_preview: false },
    ],
    seo_title: null,
    seo_description: null,
  },
  {
    id: "evidence-synthesis",
    product_type: "template",
    access_type: "paid",
    status: "unlisted",
    name: "Evidence Synthesis",
    slug: "evidence-synthesis",
    short_description: "Turn a stack of interview notes and evidence into a small number of clear findings.",
    full_description: "Interview fatigue is real: after five or ten conversations, most teams have pages of notes and no clarity. This template forces a synthesis pass — grouping evidence into themes, rating confidence per theme, and stating the finding in one sentence each.",
    outcome_statement: "A short, ranked list of findings, each backed by cited evidence.",
    target_audience: "Teams who've completed a round of interviews using the Customer Interview System.",
    when_to_use: "Use immediately after finishing a round of interviews, while the notes are fresh.",
    when_not_to_use: "Not useful with fewer than three interviews' worth of notes.",
    completion_minutes_min: 30,
    completion_minutes_max: 60,
    skill_level: "intermediate",
    current_version: "1.0",
    price_minor: 900,
    compare_at_price_minor: null,
    currency_code: "GBP",
    featured: false,
    published_at: "2026-06-20T09:00:00Z",
    scheduled_for: null,
    categories: [catRef("customer-research")],
    stages: [stageRef("understand-customers")],
    formats: ["markdown"],
    is_placeholder: true,
    licence: standardLicence,
    quality_standard: { purpose: true, instructions: true, evidenceFields: true, decisionOutcome: true },
    files: [
      { id: "evidence-synthesis-md", file_role: "template", file_format: "markdown", display_name: "Evidence Synthesis (Markdown)", is_public_preview: false },
    ],
    seo_title: null,
    seo_description: null,
  },
  {
    id: "proceed-revise-pause-decision",
    product_type: "template",
    access_type: "paid",
    status: "unlisted",
    name: "Proceed–Revise–Pause Decision",
    slug: "proceed-revise-pause-decision",
    short_description: "The closing decision template: proceed, revise or pause, with the reasoning documented for future reference.",
    full_description: "The final step of the Idea Validation Pack. Pulls together the Proven/Better/New verdict, the assumption log and the evidence synthesis into a single documented decision — proceed, revise, or pause — with the reasoning recorded so it can be revisited later.",
    outcome_statement: "A written, evidence-backed proceed/revise/pause decision with a clear next action.",
    target_audience: "Teams finishing the Idea Validation Pack.",
    when_to_use: "Use as the last step, once evidence synthesis is complete.",
    when_not_to_use: "Not useful without the evidence gathered in the earlier pack steps.",
    completion_minutes_min: 20,
    completion_minutes_max: 30,
    skill_level: "intermediate",
    current_version: "1.0",
    price_minor: 900,
    compare_at_price_minor: null,
    currency_code: "GBP",
    featured: false,
    published_at: "2026-06-20T09:00:00Z",
    scheduled_for: null,
    categories: [catRef("product-strategy")],
    stages: [stageRef("evaluate-an-idea")],
    formats: ["markdown"],
    is_placeholder: true,
    licence: standardLicence,
    quality_standard: { purpose: true, instructions: true, decisionOutcome: true, nextStep: true, reviewDate: true },
    files: [
      { id: "proceed-revise-pause-decision-md", file_role: "template", file_format: "markdown", display_name: "Proceed–Revise–Pause Decision (Markdown)", is_public_preview: false },
    ],
    seo_title: null,
    seo_description: null,
  },
];

// ---------------------------------------------------------------------------
// Product Definition Pack — 9 bundle items (spec §37)
// ---------------------------------------------------------------------------

const productDefinitionItems: Product[] = [
  {
    id: "product-vision",
    product_type: "template",
    access_type: "paid",
    status: "unlisted",
    name: "Product Vision",
    slug: "product-vision",
    short_description: "A one-page vision statement that explains where the product is going and why it matters.",
    full_description: "A short, opinionated vision statement — not a mission-statement generator. Names the change you want to see in the customer's world and why your product is the way to get there.",
    outcome_statement: "A one-page vision statement the whole team can repeat from memory.",
    target_audience: "Teams starting the Product Definition Pack after idea validation.",
    when_to_use: "Use as the first step in defining the product.",
    when_not_to_use: "Not useful before the idea has been validated — start with the Idea Validation Pack.",
    completion_minutes_min: 20,
    completion_minutes_max: 30,
    skill_level: "beginner",
    current_version: "1.0",
    price_minor: 1100,
    compare_at_price_minor: null,
    currency_code: "GBP",
    featured: false,
    published_at: "2026-07-01T09:00:00Z",
    scheduled_for: null,
    categories: [catRef("product-development")],
    stages: [stageRef("define-the-product")],
    formats: ["markdown"],
    is_placeholder: true,
    licence: standardLicence,
    quality_standard: { purpose: true, instructions: true, decisionOutcome: true },
    files: [
      { id: "product-vision-md", file_role: "template", file_format: "markdown", display_name: "Product Vision (Markdown)", is_public_preview: false },
    ],
    seo_title: null,
    seo_description: null,
  },
  {
    id: "target-user-definition",
    product_type: "template",
    access_type: "paid",
    status: "unlisted",
    name: "Target User Definition",
    slug: "target-user-definition",
    short_description: "Define your target user precisely enough that 'for everyone' is no longer an acceptable answer.",
    full_description: "Replaces vague personas with a specific definition: who the product is for right now, who it is explicitly not for yet, and how you'll recognise a target user when you meet one.",
    outcome_statement: "A specific, falsifiable definition of who the product is for.",
    target_audience: "Teams in the Product Definition Pack scoping their initial audience.",
    when_to_use: "Use after the Product Vision, before writing user needs.",
    when_not_to_use: "Not useful if you intend to serve every possible customer segment from day one.",
    completion_minutes_min: 25,
    completion_minutes_max: 35,
    skill_level: "beginner",
    current_version: "1.0",
    price_minor: 1100,
    compare_at_price_minor: null,
    currency_code: "GBP",
    featured: false,
    published_at: "2026-07-01T09:00:00Z",
    scheduled_for: null,
    categories: [catRef("product-development")],
    stages: [stageRef("define-the-product")],
    formats: ["markdown"],
    is_placeholder: true,
    licence: standardLicence,
    quality_standard: { purpose: true, instructions: true, thinkingPrompts: true },
    files: [
      { id: "target-user-definition-md", file_role: "template", file_format: "markdown", display_name: "Target User Definition (Markdown)", is_public_preview: false },
    ],
    seo_title: null,
    seo_description: null,
  },
  {
    id: "user-needs-and-scenarios",
    product_type: "template",
    access_type: "paid",
    status: "unlisted",
    name: "User Needs and Scenarios",
    slug: "user-needs-and-scenarios",
    short_description: "Document the needs and real-world scenarios your product must handle.",
    full_description: "A structured way to capture user needs as scenarios — situation, goal and desired outcome — rather than a flat feature wishlist, so the team is designing for real moments rather than abstractions.",
    outcome_statement: "A short set of scenarios the product must handle well.",
    target_audience: "Teams in the Product Definition Pack, after defining the target user.",
    when_to_use: "Use after Target User Definition, before Product Principles.",
    when_not_to_use: "Not a replacement for direct customer research if none has been done yet.",
    completion_minutes_min: 30,
    completion_minutes_max: 45,
    skill_level: "intermediate",
    current_version: "1.0",
    price_minor: 1100,
    compare_at_price_minor: null,
    currency_code: "GBP",
    featured: false,
    published_at: "2026-07-02T09:00:00Z",
    scheduled_for: null,
    categories: [catRef("product-development")],
    stages: [stageRef("define-the-product")],
    formats: ["markdown"],
    is_placeholder: true,
    licence: standardLicence,
    quality_standard: { purpose: true, instructions: true, evidenceFields: true },
    files: [
      { id: "user-needs-and-scenarios-md", file_role: "template", file_format: "markdown", display_name: "User Needs and Scenarios (Markdown)", is_public_preview: false },
    ],
    seo_title: null,
    seo_description: null,
  },
  {
    id: "product-principles",
    product_type: "template",
    access_type: "paid",
    status: "unlisted",
    name: "Product Principles",
    slug: "product-principles",
    short_description: "Write the small set of principles that will resolve disagreements when priorities conflict.",
    full_description: "A short worksheet for writing 3–5 product principles — the kind that actually change a decision, not generic values statements. Used later by the Feature Evaluation template to score candidate features.",
    outcome_statement: "3–5 written product principles the team can cite when priorities conflict.",
    target_audience: "Teams in the Product Definition Pack about to start prioritising features.",
    when_to_use: "Use after User Needs and Scenarios, before Feature Evaluation.",
    when_not_to_use: "Not useful as a branding or marketing exercise — these are internal decision principles.",
    completion_minutes_min: 25,
    completion_minutes_max: 40,
    skill_level: "intermediate",
    current_version: "1.0",
    price_minor: 1100,
    compare_at_price_minor: null,
    currency_code: "GBP",
    featured: false,
    published_at: "2026-07-02T09:00:00Z",
    scheduled_for: null,
    categories: [catRef("product-development")],
    stages: [stageRef("define-the-product")],
    formats: ["markdown"],
    is_placeholder: true,
    licence: standardLicence,
    quality_standard: { purpose: true, instructions: true, decisionOutcome: true },
    files: [
      { id: "product-principles-md", file_role: "template", file_format: "markdown", display_name: "Product Principles (Markdown)", is_public_preview: false },
    ],
    seo_title: null,
    seo_description: null,
  },
  {
    id: "feature-evaluation",
    product_type: "template",
    access_type: "paid",
    status: "unlisted",
    name: "Feature Evaluation",
    slug: "feature-evaluation",
    short_description: "Score candidate features against your product principles and user needs before committing to build them.",
    full_description: "A scoring worksheet that weighs each candidate feature against the product principles and documented user needs, producing a ranked shortlist instead of a debate settled by whoever spoke last.",
    outcome_statement: "A ranked shortlist of features with the reasoning for each score recorded.",
    target_audience: "Teams in the Product Definition Pack with a features backlog to prioritise.",
    when_to_use: "Use once Product Principles and User Needs and Scenarios are complete.",
    when_not_to_use: "Not useful without documented principles to score against.",
    completion_minutes_min: 30,
    completion_minutes_max: 60,
    skill_level: "intermediate",
    current_version: "1.0",
    price_minor: 1100,
    compare_at_price_minor: null,
    currency_code: "GBP",
    featured: false,
    published_at: "2026-07-03T09:00:00Z",
    scheduled_for: null,
    categories: [catRef("product-development")],
    stages: [stageRef("define-the-product")],
    formats: ["markdown"],
    is_placeholder: true,
    licence: standardLicence,
    quality_standard: { purpose: true, instructions: true, decisionOutcome: true },
    files: [
      { id: "feature-evaluation-md", file_role: "template", file_format: "markdown", display_name: "Feature Evaluation (Markdown)", is_public_preview: false },
    ],
    seo_title: null,
    seo_description: null,
  },
  {
    id: "mvp-scope",
    product_type: "template",
    access_type: "paid",
    status: "unlisted",
    name: "MVP Scope",
    slug: "mvp-scope",
    short_description: "The full MVP scoping template with a cut-line exercise for deciding what ships first.",
    full_description: "A fuller version of the free MVP Scope in One Page, with a cut-line exercise: rank every feature by whether the MVP fails without it, then draw the line where the evidence — not the enthusiasm — runs out.",
    outcome_statement: "A defined MVP scope with an explicit, defensible cut line.",
    target_audience: "Teams in the Product Definition Pack ready to scope a first release.",
    when_to_use: "Use after Feature Evaluation, before Product Specification.",
    when_not_to_use: "For a very small first release, the free MVP Scope in One Page may be enough.",
    completion_minutes_min: 30,
    completion_minutes_max: 45,
    skill_level: "intermediate",
    current_version: "1.0",
    price_minor: 1100,
    compare_at_price_minor: null,
    currency_code: "GBP",
    featured: false,
    published_at: "2026-07-03T09:00:00Z",
    scheduled_for: null,
    categories: [catRef("product-development")],
    stages: [stageRef("plan-the-mvp")],
    formats: ["markdown"],
    is_placeholder: true,
    licence: standardLicence,
    quality_standard: { purpose: true, instructions: true, decisionOutcome: true, nextStep: true },
    files: [
      { id: "mvp-scope-md", file_role: "template", file_format: "markdown", display_name: "MVP Scope (Markdown)", is_public_preview: false },
    ],
    seo_title: null,
    seo_description: null,
  },
  {
    id: "product-specification",
    product_type: "template",
    access_type: "paid",
    status: "unlisted",
    name: "Product Specification",
    slug: "product-specification",
    short_description: "A specification template an engineer or an AI agent can build from without guessing.",
    full_description: "Structured so that ambiguity is visible rather than hidden: required inputs, explicit non-goals, and a section for information the reader (human or AI agent) must not invent. Follows the AI-agent-ready structure described in the spec's Markdown format guidance.",
    outcome_statement: "A specification detailed enough to hand to an engineer, contractor or AI agent.",
    target_audience: "Teams and solo founders in the Product Definition Pack ready to brief development.",
    when_to_use: "Use once MVP Scope is finalised, before development starts.",
    when_not_to_use: "Not useful while scope is still actively changing week to week.",
    completion_minutes_min: 60,
    completion_minutes_max: 120,
    skill_level: "intermediate",
    current_version: "1.0",
    price_minor: 1100,
    compare_at_price_minor: null,
    currency_code: "GBP",
    featured: false,
    published_at: "2026-07-04T09:00:00Z",
    scheduled_for: null,
    categories: [catRef("product-development")],
    stages: [stageRef("define-the-product")],
    formats: ["markdown"],
    is_placeholder: true,
    licence: standardLicence,
    quality_standard: { purpose: true, inputs: true, instructions: true, decisionOutcome: true, aiAgentEdition: true },
    files: [
      { id: "product-specification-md", file_role: "template", file_format: "markdown", display_name: "Product Specification (Markdown, AI-agent-ready)", is_public_preview: false },
    ],
    seo_title: null,
    seo_description: null,
  },
  {
    id: "acceptance-criteria",
    product_type: "template",
    access_type: "paid",
    status: "unlisted",
    name: "Acceptance Criteria",
    slug: "acceptance-criteria",
    short_description: "Write acceptance criteria that make 'done' an objective, testable fact.",
    full_description: "A worksheet for turning each item in the Product Specification into testable, unambiguous acceptance criteria, so 'is this done' never becomes a matter of opinion.",
    outcome_statement: "Testable acceptance criteria attached to every item in the specification.",
    target_audience: "Teams in the Product Definition Pack finalising the specification.",
    when_to_use: "Use directly after the Product Specification.",
    when_not_to_use: "Not useful before the specification itself is written.",
    completion_minutes_min: 30,
    completion_minutes_max: 60,
    skill_level: "intermediate",
    current_version: "1.0",
    price_minor: 1100,
    compare_at_price_minor: null,
    currency_code: "GBP",
    featured: false,
    published_at: "2026-07-04T09:00:00Z",
    scheduled_for: null,
    categories: [catRef("product-development")],
    stages: [stageRef("define-the-product")],
    formats: ["markdown"],
    is_placeholder: true,
    licence: standardLicence,
    quality_standard: { purpose: true, instructions: true, decisionOutcome: true },
    files: [
      { id: "acceptance-criteria-md", file_role: "template", file_format: "markdown", display_name: "Acceptance Criteria (Markdown)", is_public_preview: false },
    ],
    seo_title: null,
    seo_description: null,
  },
  {
    id: "launch-readiness-review",
    product_type: "template",
    access_type: "paid",
    status: "unlisted",
    name: "Launch Readiness Review",
    slug: "launch-readiness-review",
    short_description: "A pre-launch checklist covering product, support and go-to-market readiness.",
    full_description: "A closing checklist for the Product Definition Pack: confirms the product, support process and go-to-market plan are genuinely ready before launch, not just that a deadline has arrived.",
    outcome_statement: "A completed readiness review with any open risks explicitly documented.",
    target_audience: "Teams in the Product Definition Pack approaching launch.",
    when_to_use: "Use in the final week before a planned launch.",
    when_not_to_use: "Not useful more than a few weeks before launch — readiness changes fast.",
    completion_minutes_min: 30,
    completion_minutes_max: 45,
    skill_level: "intermediate",
    current_version: "1.0",
    price_minor: 1100,
    compare_at_price_minor: null,
    currency_code: "GBP",
    featured: false,
    published_at: "2026-07-05T09:00:00Z",
    scheduled_for: null,
    categories: [catRef("go-to-market")],
    stages: [stageRef("prepare-to-launch")],
    formats: ["markdown"],
    is_placeholder: true,
    licence: standardLicence,
    quality_standard: { purpose: true, instructions: true, decisionOutcome: true, nextStep: true },
    files: [
      { id: "launch-readiness-review-md", file_role: "template", file_format: "markdown", display_name: "Launch Readiness Review (Markdown)", is_public_preview: false },
    ],
    seo_title: null,
    seo_description: null,
  },
];

export const products: Product[] = [...freeProducts, ...ideaValidationItems, ...productDefinitionItems];

// ---------------------------------------------------------------------------
// Bundles (spec §37 — 2 paid bundles, 9 items each)
// ---------------------------------------------------------------------------

function bundleItemsFrom(items: Product[]): BundleItem[] {
  return items.map((product, index) => ({
    product: toSummary(product),
    is_required: true,
    display_order: index,
  }));
}

export const bundles: Bundle[] = [
  {
    id: "idea-validation-pack",
    product_type: "bundle",
    access_type: "paid",
    status: "published",
    name: "Idea Validation Pack",
    slug: "idea-validation-pack",
    short_description:
      "Nine templates that take you from a raw idea to a documented proceed-revise-pause decision, backed by evidence rather than confidence.",
    full_description:
      "The Idea Validation Pack is the complete evidence-led path from a raw idea to a defensible decision. It sequences nine templates — intake, founder fit, problem evidence, competitive alternatives, a team Proven–Better–New workshop, assumption ranking, a full interview system, evidence synthesis, and a closing proceed/revise/pause decision — into a single 1–2 week process, instead of leaving you to assemble one from separate free worksheets.",
    outcome_statement:
      "A documented, evidence-based decision on whether to proceed, revise or pause — not just a folder of worksheets.",
    target_audience: "Founders who want a structured, complete path through idea validation rather than assembling their own process from free templates.",
    when_to_use: "Use end-to-end over 1–2 weeks when you're serious about validating a new idea before committing real time or money.",
    when_not_to_use: "If you only need one part of the process — for example, just customer interviews — the free Customer Interview Planner may be enough on its own.",
    completion_minutes_min: 240,
    completion_minutes_max: 480,
    skill_level: "intermediate",
    current_version: "1.0",
    price_minor: 3900,
    compare_at_price_minor: 8100,
    currency_code: "GBP",
    featured: true,
    published_at: "2026-06-22T09:00:00Z",
    scheduled_for: null,
    categories: [catRef("product-strategy")],
    stages: [stageRef("evaluate-an-idea")],
    formats: ["markdown", "pdf"],
    is_placeholder: true,
    licence: standardLicence,
    quality_standard: {
      purpose: true,
      inputs: true,
      instructions: true,
      thinkingPrompts: true,
      evidenceFields: true,
      decisionOutcome: true,
      nextStep: true,
      aiAgentEdition: true,
    },
    files: [
      {
        id: "idea-validation-pack-overview",
        file_role: "instructions",
        file_format: "markdown",
        display_name: "Pack overview and recommended order",
        is_public_preview: true,
      },
    ],
    seo_title: "Idea Validation Pack — 9-template bundle",
    seo_description:
      "Nine templates that take a raw idea to a documented proceed, revise or pause decision, backed by evidence.",
    bundle_items: bundleItemsFrom(ideaValidationItems),
  },
  {
    id: "product-definition-pack",
    product_type: "bundle",
    access_type: "paid",
    status: "published",
    name: "Product Definition Pack",
    slug: "product-definition-pack",
    short_description:
      "Nine templates that take a validated idea to a written product specification ready for design or build.",
    full_description:
      "The Product Definition Pack sequences nine templates — vision, target user, user needs and scenarios, product principles, feature evaluation, MVP scope, a full product specification, acceptance criteria, and a launch readiness review — into one connected process for turning a validated idea into a specification you can actually hand to a builder.",
    outcome_statement:
      "A complete, reviewable product definition: vision, users, scope and acceptance criteria in one connected set.",
    target_audience: "Founders and product managers defining a product after idea validation, before development starts.",
    when_to_use: "Use once you have evidence an idea is worth pursuing and need to define exactly what to build.",
    when_not_to_use: "If you haven't validated the idea yet, start with the Idea Validation Pack first.",
    completion_minutes_min: 300,
    completion_minutes_max: 600,
    skill_level: "intermediate",
    current_version: "1.0",
    price_minor: 4900,
    compare_at_price_minor: 9900,
    currency_code: "GBP",
    featured: false,
    published_at: "2026-07-06T09:00:00Z",
    scheduled_for: null,
    categories: [catRef("product-development")],
    stages: [stageRef("define-the-product")],
    formats: ["markdown"],
    is_placeholder: true,
    licence: standardLicence,
    quality_standard: {
      purpose: true,
      inputs: true,
      instructions: true,
      evidenceFields: true,
      decisionOutcome: true,
      nextStep: true,
      aiAgentEdition: true,
    },
    files: [
      {
        id: "product-definition-pack-overview",
        file_role: "instructions",
        file_format: "markdown",
        display_name: "Pack overview and recommended order",
        is_public_preview: true,
      },
    ],
    seo_title: "Product Definition Pack — 9-template bundle",
    seo_description:
      "Nine templates that take a validated idea to a written product specification ready for design or build.",
    bundle_items: bundleItemsFrom(productDefinitionItems),
  },
];

export const catalogue = { products, bundles, categories, stages, licences };

export default catalogue;
