/**
 * Seed catalogue — single source of truth for local/fixture content.
 *
 * Spec §37 seed catalogue: 8 free products, plus two paid bundles ("Idea
 * Validation Pack", "Product Definition Pack") each with 9 bundle items.
 * Every product in this file is `is_placeholder: true` — real copy pending
 * business approval (spec §37's closing line, §43.3 "clearly label seed
 * content").
 *
 * JUDGEMENT CALL (documented per plan's "seed-catalogue judgment calls"):
 * "Copy–Improve–Differentiate Assessment" appears both as a standalone free product
 * AND in the spec's literal Idea Validation Pack item list. Re-using the
 * same product in both places would make the bundle's "combined price"
 * calculation nonsensical (you can't sell the same free item for money as
 * part of a paid bundle without it being a different SKU). So the bundle's
 * copy is a distinct, deeper paid product with its own slug
 * (`proven-better-new-assessment-pro`) rather than a re-listing of the free
 * `proven-better-new-assessment`.
 *
 * JUDGEMENT CALL: bundle items don't need to be independently browsable —
 * they exist as real product rows (so `bundle_items` has something to
 * reference and so a future product page could be built for them) but are
 * given `status: 'unlisted'` rather than `'published'`. Unlisted products
 * are intentionally excluded from `searchCatalogue` results and the public
 * catalogue by `fixture-source.ts` while still being valid records.
 *
 * JUDGEMENT CALL (deliberate deviation from spec §37's literal "seed as
 * draft", approved in the build plan's "Decisions locked in" section): most
 * products are `status: 'published'` so the catalogue is actually
 * browsable. Exactly two are left `'draft'` and exactly one `'scheduled'`
 * (with a future `scheduled_for`) specifically so the visibility-filtering
 * logic in `fixture-source.ts` can be exercised and tested.
 *
 * No real cover/preview images exist yet (no Storage bucket, no admin
 * upload). Product/file records deliberately omit any image URL field so
 * the UI renders its designed placeholder cover state rather than a broken
 * `<img>`.
 *
 * v3 additions (see docs/Incytemplates-website-spec-v3.md and docs/decisions):
 * - `stages` now holds the v3 7-stage journey (idea/validate/decide/design/
 *   build/launch/improve), replacing the v2 8-stage taxonomy. Every existing
 *   product's `stages` reference was remapped to the nearest new stage.
 * - `frameworks` is new: the reusable method/problem/outcome layer above
 *   individual Guide/Template/Tool outputs. Product Idea Assessor is fully
 *   populated and published; the other five flagship families are minimal,
 *   draft, flagship placeholders (public "Coming soon" teasers only).
 * - `products` gained `guide`/`tool`-typed rows for the Product Idea
 *   Assessor family, and the existing `proven-better-new-assessment`
 *   Template was reassigned into that same framework rather than duplicated.
 */

import type {
  Bundle,
  BundleItem,
  Category,
  Framework,
  Licence,
  Product,
  ProductSummary,
  Stage,
} from "@/types/catalogue";

// ---------------------------------------------------------------------------
// Categories (spec §7.1 — 7 categories)
// ---------------------------------------------------------------------------

export const categories: Category[] = [
  {
    id: "cat-product-development",
    name: "Product development",
    slug: "product-development",
    description: "Templates for scoping, specifying and shipping a product.",
    display_order: 1,
  },
  {
    id: "cat-business-startup",
    name: "Business & startup",
    slug: "business-startup",
    description: "Templates for starting and running an early-stage business.",
    display_order: 2,
  },
  {
    id: "cat-customer-research",
    name: "Customer research",
    slug: "customer-research",
    description: "Templates for planning, running and synthesising customer research.",
    display_order: 3,
  },
  {
    id: "cat-product-strategy",
    name: "Product strategy",
    slug: "product-strategy",
    description: "Templates for evaluating ideas and setting product direction.",
    display_order: 4,
  },
  {
    id: "cat-business-planning",
    name: "Business planning",
    slug: "business-planning",
    description: "Templates for planning the commercial side of the business.",
    display_order: 5,
  },
  {
    id: "cat-go-to-market",
    name: "Go-to-market",
    slug: "go-to-market",
    description: "Templates for planning and preparing a launch.",
    display_order: 6,
  },
  {
    id: "cat-founder-management",
    name: "Founder management",
    slug: "founder-management",
    description: "Templates for reviewing progress and managing yourself as a founder.",
    display_order: 7,
  },
];

// ---------------------------------------------------------------------------
// Stages (spec v3 §7/§8/§14.6 — 7 canonical journey stages, replacing the v2
// 8-stage taxonomy: find-a-problem, evaluate-an-idea, understand-customers,
// define-the-product, test-demand, plan-the-mvp, prepare-to-launch,
// review-and-improve. Every product's `stages` reference below was remapped
// to the nearest new stage — see docs/decisions for the mapping table and
// the one deliberate exception (proceed-revise-pause-decision -> decide).
// ---------------------------------------------------------------------------

export const stages: Stage[] = [
  {
    id: "stage-idea",
    name: "Idea",
    slug: "idea",
    description: "Find and frame a problem worth solving.",
    display_order: 1,
  },
  {
    id: "stage-validate",
    name: "Validate",
    slug: "validate",
    description: "Gather evidence on the problem, the idea and your customers before committing.",
    display_order: 2,
  },
  {
    id: "stage-decide",
    name: "Decide",
    slug: "decide",
    description: "Reach a documented decision on whether and how to proceed.",
    display_order: 3,
  },
  {
    id: "stage-design",
    name: "Design",
    slug: "design",
    description: "Turn a validated idea into a precise, buildable product definition.",
    display_order: 4,
  },
  {
    id: "stage-build",
    name: "Build",
    slug: "build",
    description: "Scope and build the smallest useful version worth testing.",
    display_order: 5,
  },
  {
    id: "stage-launch",
    name: "Launch",
    slug: "launch",
    description: "Get the product, support and go-to-market ready, then release it.",
    display_order: 6,
  },
  {
    id: "stage-improve",
    name: "Improve",
    slug: "improve",
    description: "Review progress on a regular cadence and decide what to do next.",
    display_order: 7,
  },
];

// ---------------------------------------------------------------------------
// Licences
// ---------------------------------------------------------------------------

export const licences: Licence[] = [
  {
    id: "lic-standard-personal-commercial",
    name: "Standard Personal & Commercial Use",
    slug: "standard-personal-commercial-use",
    summary:
      "Single-purchaser licence covering personal and commercial use, including client work. Redistribution or resale of the template itself is not permitted.",
    commercial_use_allowed: true,
    client_work_allowed: true,
    redistribution_allowed: false,
  },
];

const standardLicence = licences[0]!;

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function catRef(slug: string): Pick<Category, "slug" | "name"> {
  const category = categories.find((c) => c.slug === slug);
  if (!category) throw new Error(`Unknown category slug in seed data: ${slug}`);
  return { slug: category.slug, name: category.name };
}

function stageRef(slug: string): Pick<Stage, "slug" | "name"> {
  const stage = stages.find((s) => s.slug === slug);
  if (!stage) throw new Error(`Unknown stage slug in seed data: ${slug}`);
  return { slug: stage.slug, name: stage.name };
}

export function toSummary(product: Product): ProductSummary {
  const {
    id,
    product_type,
    access_type,
    status,
    name,
    slug,
    short_description,
    outcome_statement,
    completion_minutes_min,
    completion_minutes_max,
    skill_level,
    price_minor,
    compare_at_price_minor,
    currency_code,
    featured,
    published_at,
    scheduled_for,
    categories: cats,
    stages: stgs,
    formats,
    is_placeholder,
    framework_id,
    tool_key,
  } = product;
  return {
    id,
    product_type,
    access_type,
    status,
    name,
    slug,
    short_description,
    outcome_statement,
    completion_minutes_min,
    completion_minutes_max,
    skill_level,
    price_minor,
    compare_at_price_minor,
    currency_code,
    featured,
    published_at,
    scheduled_for,
    categories: cats,
    stages: stgs,
    formats,
    is_placeholder,
    framework_id,
    tool_key,
  };
}

// ---------------------------------------------------------------------------
// Frameworks (spec v3 §14.3, §37) — the reusable method/problem/outcome layer
// above individual Guide/Template/Tool outputs. Product Idea Assessor,
// Customer Discovery Kit and Better Decision Maker are fully populated and
// published, each with a complete Guide/Template/Tool set (see
// docs/decisions/0021 for how Customer Discovery Kit reused existing
// v2-era template/guide content, and docs/decisions/0022 for Better
// Decision Maker, built entirely from new content). The remaining three
// flagship families (spec v3 §37.1 Tier 1) are seeded as minimal, draft,
// flagship placeholders per the product-owner decision recorded in
// docs/decisions — visible as public "Coming soon" teasers (via
// `it_frameworks_teasers`/`getFrameworkTeasers`), not full pages, and with
// no child Guide/Template/Tool rows yet.
// ---------------------------------------------------------------------------

export const PRODUCT_IDEA_ASSESSOR_FRAMEWORK_ID = "framework-product-idea-assessor";
export const CUSTOMER_DISCOVERY_KIT_FRAMEWORK_ID = "framework-customer-discovery-kit";
export const BETTER_DECISION_MAKER_FRAMEWORK_ID = "framework-better-decision-maker";

export const frameworks: Framework[] = [
  {
    id: PRODUCT_IDEA_ASSESSOR_FRAMEWORK_ID,
    status: "published",
    name: "Product Idea Assessor",
    slug: "product-idea-assessor",
    short_description: "Work out how much evidence your idea actually needs before you commit real time or money to it.",
    problem_statement:
      "Founders routinely over-invest in ideas that needed more validation, and under-invest in ideas that needed less — because nothing tells them how much scepticism a given idea actually deserves before they start.",
    outcome_statement:
      "A Copy/Improve/Differentiate classification, a scored read on how strong your evidence is, and a clear next action.",
    target_audience: "Solo founders and early-stage teams deciding how cautiously to approach a specific idea.",
    when_to_use: "Use as soon as you can state the idea in a sentence, before you've written a business plan or built anything.",
    when_not_to_use:
      "Not a substitute for actually talking to customers — it tells you how much evidence you need, not whether you already have it.",
    method_summary:
      "Classify the idea as Copy (a working model applied to a new context), Improve (a specific improvement on an existing, working approach) or Differentiate (asking people to adopt a genuinely new behaviour). Each category carries a different risk profile and needs a different amount of evidence before you commit. Answer four evidence questions — problem evidence, behaviour evidence, differentiation clarity and target specificity — and the assessor combines your classification with those answers into a readiness verdict and a concrete next step.",
    journey_stage: stageRef("validate"),
    priority_score: 96,
    priority_rationale:
      "Ranked #1 in the source-material opportunity portfolio (spec v3 §37): broad audience fit, strong existing source material, and it establishes the reusable Guide/Template/Tool pattern every later family follows.",
    source_strength: "strong",
    source_note: "Developed from A Bit Gamey material on testing product ideas before building, including the Copy–Improve–Differentiate classification.",
    flagship: true,
    display_order: 1,
    seo_title: "Product Idea Assessor — is this idea worth pursuing?",
    seo_description:
      "Classify your idea as Copy, Improve or Differentiate and get a scored, evidence-based read on whether it's ready to proceed.",
    published_at: "2026-08-01T09:00:00Z",
    next_step_framework_slug: "customer-discovery-kit",
  },
  {
    id: CUSTOMER_DISCOVERY_KIT_FRAMEWORK_ID,
    status: "published",
    name: "Customer Discovery Kit",
    slug: "customer-discovery-kit",
    short_description: "Find out what potential customers actually do and need, without leading them to agree with you.",
    problem_statement:
      "Founders run interview after interview, but the interviews are shaped by what they already believe: leading questions, pitching before listening, and treating polite interest as evidence. The round feels productive and produces nothing anyone can actually act on.",
    outcome_statement: "A set of customer conversations that produce real evidence instead of polite agreement.",
    target_audience: "Founders about to run their first — or next — round of customer discovery.",
    when_to_use: "Use once the Product Idea Assessor says you need more evidence, before you write a business plan or start building anything.",
    when_not_to_use:
      "Not useful once you already have paying customers to learn from — this is for early, pre-build discovery, not ongoing customer feedback.",
    method_summary:
      "Plan who to talk to and build a script that asks about people's past and present, not their hypothetical future (the Customer Interview Planner). Get as far as you can into understanding their situation before you mention your idea at all, ask 'why' past the first, rehearsed answer, and write down what surprised you immediately after each conversation, logged against your assumptions rather than mixed in with tasks (the Assumption and Evidence Tracker). Keep going until interviews stop surprising you. The Evidence Analyser Tool then scores what you've gathered — how many people, how open your questions really were, whether you heard real past behaviour or just opinions, whether anyone showed a costly commitment, and whether a pattern is actually forming — and caps the score when leading questions mean the pattern itself can't be trusted yet.",
    journey_stage: stageRef("validate"),
    priority_score: 95,
    priority_rationale:
      "Ranked #2 in the source-material opportunity portfolio (spec v3 §37): the natural next step after Product Idea Assessor, and existing Customer Interview Planner / Assumption and Evidence Tracker templates plus a mature interview-technique guide meant this family could be completed without writing new template content from scratch.",
    source_strength: "strong",
    source_note:
      "Developed from A Bit Gamey material on running customer interviews that avoid leading questions and confirmation bias, including the 'ask about the past, not the future' and 'stop pitching before the interview starts' techniques.",
    flagship: true,
    display_order: 2,
    seo_title: "Customer Discovery Kit — turn customer conversations into real evidence",
    seo_description:
      "Plan interviews that avoid leading questions, log what you learn separately from what you're assuming, and score how strong your evidence actually is.",
    published_at: "2026-08-09T09:00:00Z",
    next_step_framework_slug: "better-decision-maker",
  },
  {
    id: BETTER_DECISION_MAKER_FRAMEWORK_ID,
    status: "published",
    name: "Better Decision Maker",
    slug: "better-decision-maker",
    short_description: "Given the evidence you have, work out what you should actually do.",
    problem_statement:
      "Founders wait for certainty that never arrives, or decide on instinct without noticing that some decisions are cheap to reverse and others aren't — so easy, reversible calls get over-analysed while genuinely risky, one-way ones get rushed.",
    outcome_statement: "A documented decision, reasoned through rather than made on instinct alone.",
    target_audience: "Founders facing an important decision under uncertainty.",
    when_to_use: "Use once you have real options to weigh — after the evidence-gathering stages, not instead of them.",
    when_not_to_use:
      "Not useful for decisions that are genuinely reversible and low-stakes — the process itself costs more time than a quick two-way-door decision deserves.",
    method_summary:
      "Classify the decision by reversibility first: a two-way door is cheap to back out of and deserves a fast call; a one-way door is expensive or impossible to reverse and deserves real analysis. Invert the question — instead of 'what would make this succeed,' ask 'what would guarantee it fails' — to turn an abstract comparison into a concrete checklist of what to avoid. Check the decision against any simple rules you've already committed to, so routine decisions don't need fresh analysis every time. For decisions with real options to compare, estimate expected value for each — likelihood of success, impact if it works, and effort to attempt — and when two options come out close, let reversibility break the tie rather than agonising further.",
    journey_stage: stageRef("decide"),
    priority_score: 94,
    priority_rationale:
      "Ranked #3 in the source-material opportunity portfolio (spec v3 §37): the natural next step once Product Idea Assessor and Customer Discovery Kit have produced evidence — this family is where that evidence actually turns into a decision.",
    source_strength: "strong",
    source_note:
      "Developed from A Bit Gamey material on decision-making under uncertainty, including reversibility ('two-way door' vs 'one-way door'), inversion, simple rules and expected-value estimation.",
    flagship: true,
    display_order: 3,
    seo_title: "Better Decision Maker — decide under uncertainty without waiting for certainty",
    seo_description:
      "Four techniques for making an important founder decision: reversibility, inversion, simple rules and expected value — with a worksheet and a comparison tool.",
    published_at: "2026-08-09T09:00:00Z",
    next_step_framework_slug: "mvp-scoper",
  },
  {
    id: "framework-mvp-scoper",
    status: "draft",
    name: "MVP Scoper",
    slug: "mvp-scoper",
    short_description: "Work out the smallest useful version of your product worth building first.",
    problem_statement: null,
    outcome_statement: "A scoped MVP with what's in, what's explicitly out, and the riskiest question it needs to answer.",
    target_audience: "Founders and small product teams about to start building.",
    when_to_use: null,
    when_not_to_use: null,
    method_summary: null,
    journey_stage: stageRef("build"),
    priority_score: 92,
    priority_rationale: "Ranked #5 in the source-material opportunity portfolio (spec v3 §37).",
    source_strength: null,
    source_note: null,
    flagship: true,
    display_order: 4,
    seo_title: null,
    seo_description: null,
    published_at: null,
    next_step_framework_slug: null,
  },
  {
    id: "framework-product-naming-system",
    status: "draft",
    name: "Product Naming System",
    slug: "product-naming-system",
    short_description: "Choose a product name using weighted criteria instead of whoever argues loudest in the room.",
    problem_statement: null,
    outcome_statement: "A shortlist of names scored against the criteria that actually matter for this product.",
    target_audience: "Founders and product teams naming a new product.",
    when_to_use: null,
    when_not_to_use: null,
    method_summary: null,
    journey_stage: stageRef("design"),
    priority_score: 93,
    priority_rationale: "Ranked #4 in the source-material opportunity portfolio (spec v3 §37).",
    source_strength: null,
    source_note: null,
    flagship: true,
    display_order: 5,
    seo_title: null,
    seo_description: null,
    published_at: null,
    next_step_framework_slug: null,
  },
  {
    id: "framework-first-customers-planner",
    status: "draft",
    name: "First Customers Planner",
    slug: "first-customers-planner",
    short_description: "Plan how you'll find your first customers instead of hoping they find you.",
    problem_statement: null,
    outcome_statement: "A prioritised plan for reaching a first set of real customers.",
    target_audience: "Founders approaching launch who don't yet have a customer-acquisition plan.",
    when_to_use: null,
    when_not_to_use: null,
    method_summary: null,
    journey_stage: stageRef("launch"),
    priority_score: 90,
    priority_rationale: "Ranked #7 in the source-material opportunity portfolio (spec v3 §37).",
    source_strength: null,
    source_note: null,
    flagship: true,
    display_order: 6,
    seo_title: null,
    seo_description: null,
    published_at: null,
    next_step_framework_slug: null,
  },
];

// ---------------------------------------------------------------------------
// Free products (spec §37 — 8 free products)
// ---------------------------------------------------------------------------

const freeProducts: Product[] = [
  {
    id: "product-idea-snapshot",
    product_type: "template",
    access_type: "free",
    status: "published",
    name: "Product Idea Snapshot",
    slug: "product-idea-snapshot",
    short_description:
      "A one-page worksheet that turns a vague idea into a testable statement of who it's for, what problem it solves, and why now.",
    full_description:
      "Most ideas don't fail because they're bad — they fail because they're vague. The Product Idea Snapshot forces you to state the problem, the customer, the proposed solution and your riskiest assumption on a single page, in plain language. It's the fastest way to find out whether an idea is specific enough to test, and it's the template every other Incy Templates worksheet assumes you've already completed.",
    outcome_statement:
      "Leave with a single-page snapshot you can show a co-founder, mentor or customer in under two minutes.",
    target_audience:
      "Solo founders and early-stage teams who have an idea but haven't written it down in a form anyone else could evaluate.",
    when_to_use: "Use this in the first hour of taking an idea seriously, before you've spent time building or researching.",
    when_not_to_use:
      "Not for ideas you've already validated with real customers — move on to the Copy–Improve–Differentiate Assessment instead.",
    completion_minutes_min: 15,
    completion_minutes_max: 25,
    skill_level: "beginner",
    current_version: "1.0",
    price_minor: null,
    compare_at_price_minor: null,
    currency_code: "GBP",
    featured: true,
    published_at: "2026-06-02T09:00:00Z",
    scheduled_for: null,
    categories: [catRef("product-strategy")],
    stages: [stageRef("validate")],
    formats: ["markdown", "pdf"],
    is_placeholder: true,
    framework_id: null,
    tool_key: null,
    licence: standardLicence,
    quality_standard: {
      purpose: true,
      inputs: true,
      instructions: true,
      completedExample: true,
      thinkingPrompts: true,
      decisionOutcome: true,
      aiAgentEdition: true,
    },
    files: [
      {
        id: "product-idea-snapshot-md",
        file_role: "template",
        file_format: "markdown",
        display_name: "Product Idea Snapshot (Markdown, AI-agent-ready)",
        is_public_preview: false,
      },
      {
        id: "product-idea-snapshot-example",
        file_role: "example",
        file_format: "pdf",
        display_name: "Completed example: a subscription meal-kit idea",
        is_public_preview: true,
      },
    ],
    seo_title: "Product Idea Snapshot — free one-page template",
    seo_description:
      "A free one-page worksheet that turns a vague idea into a testable statement of the customer, problem and riskiest assumption.",
  },
  {
    id: "proven-better-new-assessment",
    product_type: "template",
    access_type: "free",
    status: "published",
    name: "Copy–Improve–Differentiate Assessment",
    slug: "proven-better-new-assessment",
    short_description:
      "Classify your idea as Copy, Improve or Differentiate so you know how much evidence you actually need before committing.",
    full_description:
      "The Copy–Improve–Differentiate method (see the Product Idea Assessor guide) separates ideas that copy a working model, ideas that improve on an existing one, and ideas that introduce genuinely new behaviour. Each category carries a different risk profile and needs a different amount of validation before you commit real time or money. This worksheet walks you through the classification and hands you the evidence checklist that follows from your answer.",
    outcome_statement:
      "A clear verdict — Copy, Improve or Differentiate — plus the specific evidence that verdict requires before you proceed.",
    target_audience: "Founders and product people deciding how cautiously to approach an idea.",
    when_to_use: "Use immediately after the Product Idea Snapshot, before writing a business plan or building anything.",
    when_not_to_use:
      "Not a substitute for actual customer interviews — it tells you how much evidence you need, not whether you have it yet.",
    completion_minutes_min: 20,
    completion_minutes_max: 30,
    skill_level: "beginner",
    current_version: "1.1",
    price_minor: null,
    compare_at_price_minor: null,
    currency_code: "GBP",
    featured: true,
    published_at: "2026-06-02T09:00:00Z",
    scheduled_for: null,
    categories: [catRef("product-strategy")],
    stages: [stageRef("validate")],
    formats: ["markdown", "pdf"],
    is_placeholder: true,
    framework_id: PRODUCT_IDEA_ASSESSOR_FRAMEWORK_ID,
    tool_key: null,
    licence: standardLicence,
    quality_standard: {
      purpose: true,
      inputs: true,
      instructions: true,
      thinkingPrompts: true,
      evidenceFields: true,
      decisionOutcome: true,
      aiAgentEdition: true,
    },
    files: [
      {
        id: "proven-better-new-assessment-md",
        file_role: "template",
        file_format: "markdown",
        display_name: "Copy–Improve–Differentiate Assessment (Markdown, AI-agent-ready)",
        is_public_preview: false,
      },
      {
        id: "proven-better-new-assessment-example",
        file_role: "example",
        file_format: "pdf",
        display_name: "Completed example: a B2B invoicing idea",
        is_public_preview: true,
      },
    ],
    seo_title: "Copy–Improve–Differentiate Assessment — free idea evaluation template",
    seo_description:
      "Classify an idea as Copy, Improve or Differentiate and get the evidence checklist that follows, free.",
  },
  {
    id: "problem-definition-worksheet",
    product_type: "template",
    access_type: "free",
    status: "published",
    name: "Problem Definition Worksheet",
    slug: "problem-definition-worksheet",
    short_description:
      "A structured worksheet for writing a problem statement that's specific enough to test, instead of a hunch.",
    full_description:
      "Deliberately solution-free. This worksheet asks you to name the audience, the frequency of the problem, the current cost of it going unsolved, and the evidence you already have (versus what you're assuming). Teams that skip this step tend to build solutions to problems nobody can actually describe.",
    outcome_statement:
      "A one-paragraph problem statement with a named audience, a frequency, and a cost of the problem going unsolved.",
    target_audience: "Anyone starting from 'people struggle with X' who needs to make that concrete.",
    when_to_use: "Use before you've decided on a solution — this worksheet is deliberately solution-free.",
    when_not_to_use:
      "Not useful once you've already committed to a specific product direction; use the Product Specification instead.",
    completion_minutes_min: 20,
    completion_minutes_max: 30,
    skill_level: "beginner",
    current_version: "1.0",
    price_minor: null,
    compare_at_price_minor: null,
    currency_code: "GBP",
    featured: false,
    published_at: "2026-06-05T09:00:00Z",
    scheduled_for: null,
    categories: [catRef("customer-research")],
    stages: [stageRef("idea")],
    formats: ["markdown", "pdf"],
    is_placeholder: true,
    framework_id: null,
    tool_key: null,
    licence: standardLicence,
    quality_standard: {
      purpose: true,
      inputs: true,
      instructions: true,
      thinkingPrompts: true,
      evidenceFields: true,
      nextStep: true,
    },
    files: [
      {
        id: "problem-definition-worksheet-md",
        file_role: "template",
        file_format: "markdown",
        display_name: "Problem Definition Worksheet (Markdown)",
        is_public_preview: false,
      },
      {
        id: "problem-definition-worksheet-example",
        file_role: "example",
        file_format: "pdf",
        display_name: "Completed example: late invoice chasing",
        is_public_preview: true,
      },
    ],
    seo_title: "Problem Definition Worksheet — free template",
    seo_description: "Write a problem statement specific enough to test, free, in about 20 minutes.",
  },
  {
    id: "existing-alternatives-review",
    product_type: "template",
    access_type: "free",
    // Deliberately left `scheduled` (see file header) to prove scheduled
    // products are hidden from public queries until scheduled_for passes.
    status: "scheduled",
    name: "Existing Alternatives Review",
    slug: "existing-alternatives-review",
    short_description:
      "A side-by-side review of how people currently solve the problem — including doing nothing — so you know what you're really competing with.",
    full_description:
      "Founders who say 'we have no competitors' usually mean 'no other venture-backed startup does exactly this.' This worksheet widens the lens: spreadsheets, manual workarounds, competitors' adjacent products, and doing nothing are all alternatives your idea has to beat. You'll come away with a comparison table and a clearer view of the switching cost customers actually face.",
    outcome_statement:
      "A comparison table of 4–6 alternatives with their strengths, weaknesses and the switching cost people face.",
    target_audience: "Founders who assume 'no direct competitors' means 'no alternatives'.",
    when_to_use: "Use once you've defined the problem, before designing a solution.",
    when_not_to_use: "Not a substitute for direct customer conversations about why they haven't switched already.",
    completion_minutes_min: 30,
    completion_minutes_max: 45,
    skill_level: "beginner",
    current_version: "1.0",
    price_minor: null,
    compare_at_price_minor: null,
    currency_code: "GBP",
    featured: false,
    published_at: null,
    scheduled_for: "2026-08-18T09:00:00Z",
    categories: [catRef("product-strategy")],
    stages: [stageRef("idea")],
    formats: ["markdown", "pdf"],
    is_placeholder: true,
    framework_id: null,
    tool_key: null,
    licence: standardLicence,
    quality_standard: {
      purpose: true,
      inputs: true,
      instructions: true,
      evidenceFields: true,
    },
    files: [
      {
        id: "existing-alternatives-review-md",
        file_role: "template",
        file_format: "markdown",
        display_name: "Existing Alternatives Review (Markdown)",
        is_public_preview: false,
      },
    ],
    seo_title: "Existing Alternatives Review — free template",
    seo_description: "Review the real alternatives to your idea, including doing nothing, free.",
  },
  {
    id: "customer-interview-planner",
    product_type: "template",
    access_type: "free",
    status: "published",
    name: "Customer Interview Planner",
    slug: "customer-interview-planner",
    short_description: "Plan a round of customer interviews that produce evidence instead of polite agreement.",
    full_description:
      "Includes a target-list worksheet for deciding who to talk to and why, and an interview script built to avoid leading questions — the single most common way founders accidentally confirm what they already believed. Works for five interviews or fifteen.",
    outcome_statement: "A ready-to-use interview script and a target list of who to talk to and why.",
    target_audience: "Founders about to run their first — or next — round of customer interviews.",
    when_to_use: "Use before you contact anyone; the script is built to avoid leading questions.",
    when_not_to_use: "Not for feedback on an already-shipped feature with existing paying customers.",
    completion_minutes_min: 25,
    completion_minutes_max: 40,
    skill_level: "beginner",
    current_version: "1.2",
    price_minor: null,
    compare_at_price_minor: null,
    currency_code: "GBP",
    featured: true,
    published_at: "2026-06-10T09:00:00Z",
    scheduled_for: null,
    categories: [catRef("customer-research")],
    stages: [stageRef("validate")],
    formats: ["markdown", "pdf"],
    is_placeholder: true,
    framework_id: CUSTOMER_DISCOVERY_KIT_FRAMEWORK_ID,
    tool_key: null,
    licence: standardLicence,
    quality_standard: {
      purpose: true,
      inputs: true,
      instructions: true,
      thinkingPrompts: true,
      evidenceFields: true,
      nextStep: true,
      aiAgentEdition: true,
    },
    files: [
      {
        id: "customer-interview-planner-md",
        file_role: "template",
        file_format: "markdown",
        display_name: "Customer Interview Planner (Markdown, AI-agent-ready)",
        is_public_preview: false,
      },
      {
        id: "customer-interview-planner-example",
        file_role: "example",
        file_format: "pdf",
        display_name: "Completed example: interview plan for a scheduling tool",
        is_public_preview: true,
      },
    ],
    seo_title: "Customer Interview Planner — free template",
    seo_description: "Plan customer interviews that produce real evidence, free, with a ready-to-use script.",
  },
  {
    id: "assumption-and-evidence-tracker",
    product_type: "template",
    access_type: "free",
    status: "published",
    name: "Assumption and Evidence Tracker",
    slug: "assumption-and-evidence-tracker",
    short_description:
      "A running log that separates what you're assuming from what you've actually confirmed with evidence.",
    full_description:
      "A single source of truth for 'do we actually know this, or are we assuming it.' Start it the day you begin customer research and keep it updated as evidence comes in — it becomes the backbone of every proceed/revise/pause decision you make afterwards.",
    outcome_statement:
      "A prioritised list of your riskiest unconfirmed assumptions and what evidence would resolve them.",
    target_audience: "Teams who want one place to track beliefs, not just tasks.",
    when_to_use: "Start it the day you begin customer research and keep it updated throughout.",
    when_not_to_use: "Not a project-management tool — it tracks beliefs, not tasks or deadlines.",
    completion_minutes_min: 15,
    completion_minutes_max: 20,
    skill_level: "beginner",
    current_version: "1.0",
    price_minor: null,
    compare_at_price_minor: null,
    currency_code: "GBP",
    featured: false,
    published_at: "2026-06-12T09:00:00Z",
    scheduled_for: null,
    categories: [catRef("customer-research")],
    stages: [stageRef("validate")],
    formats: ["markdown"],
    is_placeholder: true,
    framework_id: CUSTOMER_DISCOVERY_KIT_FRAMEWORK_ID,
    tool_key: null,
    licence: standardLicence,
    quality_standard: {
      purpose: true,
      instructions: true,
      evidenceFields: true,
      decisionOutcome: true,
      aiAgentEdition: true,
    },
    files: [
      {
        id: "assumption-and-evidence-tracker-md",
        file_role: "template",
        file_format: "markdown",
        display_name: "Assumption and Evidence Tracker (Markdown, AI-agent-ready)",
        is_public_preview: false,
      },
    ],
    seo_title: "Assumption and Evidence Tracker — free template",
    seo_description: "Separate what you're assuming from what you've confirmed with evidence, free.",
  },
  {
    id: "mvp-scope-in-one-page",
    product_type: "template",
    access_type: "free",
    status: "published",
    name: "MVP Scope in One Page",
    slug: "mvp-scope-in-one-page",
    short_description:
      "Force your MVP onto a single page: what's in, what's explicitly out, and the one question it needs to answer.",
    full_description:
      "A short, deliberately restrictive scoping template for a first release. Naming what's explicitly out is as important as naming what's in — this is the page you hold up when someone suggests 'just one more feature' before launch.",
    outcome_statement:
      "A one-page scope you can hold yourself to when the temptation to add 'just one more feature' shows up.",
    target_audience: "Founders and small product teams about to start building.",
    when_to_use: "Use once you have a validated problem and a rough solution direction.",
    when_not_to_use:
      "Not for teams past their first release — see the Product Definition Pack's fuller MVP Scope template.",
    completion_minutes_min: 20,
    completion_minutes_max: 30,
    skill_level: "beginner",
    current_version: "1.0",
    price_minor: null,
    compare_at_price_minor: null,
    currency_code: "GBP",
    featured: true,
    published_at: "2026-06-15T09:00:00Z",
    scheduled_for: null,
    categories: [catRef("product-development")],
    stages: [stageRef("build")],
    formats: ["markdown", "pdf"],
    is_placeholder: true,
    framework_id: null,
    tool_key: null,
    licence: standardLicence,
    quality_standard: {
      purpose: true,
      instructions: true,
      decisionOutcome: true,
      nextStep: true,
      aiAgentEdition: true,
    },
    files: [
      {
        id: "mvp-scope-in-one-page-md",
        file_role: "template",
        file_format: "markdown",
        display_name: "MVP Scope in One Page (Markdown, AI-agent-ready)",
        is_public_preview: false,
      },
      {
        id: "mvp-scope-in-one-page-example",
        file_role: "example",
        file_format: "pdf",
        display_name: "Completed example: MVP scope for a booking app",
        is_public_preview: true,
      },
    ],
    seo_title: "MVP Scope in One Page — free template",
    seo_description: "Scope your MVP on a single page: what's in, what's out, free.",
  },
  {
    id: "weekly-founder-review",
    product_type: "template",
    access_type: "free",
    // Deliberately left `draft` (see file header) to prove draft products
    // are hidden from public queries.
    status: "draft",
    name: "Weekly Founder Review",
    slug: "weekly-founder-review",
    short_description: "A 15-minute weekly ritual for reviewing progress, evidence gathered, and what to do differently next week.",
    full_description:
      "A lightweight replacement for a formal retro, built for teams of one to three people. Three questions, answered in writing, every week: what did we learn, what changed as a result, and what do we do next. Still being finalised before publication.",
    outcome_statement: "A short written answer to: what did we learn, what changed, what do we do next.",
    target_audience: "Solo founders and small teams who want a lightweight replacement for a formal retro.",
    when_to_use: "Run it at the same time every week, ideally Friday afternoon or Monday morning.",
    when_not_to_use: "Not a replacement for a formal board update once you have investors.",
    completion_minutes_min: 10,
    completion_minutes_max: 15,
    skill_level: "beginner",
    current_version: "0.9",
    price_minor: null,
    compare_at_price_minor: null,
    currency_code: "GBP",
    featured: false,
    published_at: null,
    scheduled_for: null,
    categories: [catRef("founder-management")],
    stages: [stageRef("improve")],
    formats: ["markdown"],
    is_placeholder: true,
    framework_id: null,
    tool_key: null,
    licence: standardLicence,
    quality_standard: {
      purpose: true,
      instructions: true,
      nextStep: true,
    },
    files: [
      {
        id: "weekly-founder-review-md",
        file_role: "template",
        file_format: "markdown",
        display_name: "Weekly Founder Review (Markdown)",
        is_public_preview: false,
      },
    ],
    seo_title: "Weekly Founder Review — free template",
    seo_description: "A 15-minute weekly review ritual for solo founders and small teams, free.",
  },
];

// ---------------------------------------------------------------------------
// Idea Validation Pack — 9 bundle items (spec §37)
// ---------------------------------------------------------------------------

const ideaValidationItems: Product[] = [
  {
    id: "idea-intake",
    product_type: "template",
    access_type: "paid",
    status: "unlisted",
    name: "Idea Intake",
    slug: "idea-intake",
    short_description: "A structured intake form that captures the idea, its source, and why it's worth evaluating now.",
    full_description: "The opening step of the Idea Validation Pack: a short, structured intake that captures the idea, where it came from, and the reason it's being taken seriously right now.",
    outcome_statement: "A one-page record of the idea as it stood on day one, for later comparison.",
    target_audience: "Founders starting the Idea Validation Pack.",
    when_to_use: "Use as the first step of the pack, before any evaluation begins.",
    when_not_to_use: "Not needed if you've already completed the free Product Idea Snapshot for this idea.",
    completion_minutes_min: 10,
    completion_minutes_max: 15,
    skill_level: "beginner",
    current_version: "1.0",
    price_minor: 900,
    compare_at_price_minor: null,
    currency_code: "GBP",
    featured: false,
    published_at: "2026-06-18T09:00:00Z",
    scheduled_for: null,
    categories: [catRef("product-strategy")],
    stages: [stageRef("validate")],
    formats: ["markdown"],
    is_placeholder: true,
    framework_id: null,
    tool_key: null,
    licence: standardLicence,
    quality_standard: { purpose: true, instructions: true },
    files: [
      { id: "idea-intake-md", file_role: "template", file_format: "markdown", display_name: "Idea Intake (Markdown)", is_public_preview: false },
    ],
    seo_title: null,
    seo_description: null,
  },
  {
    id: "founder-fit-assessment",
    product_type: "template",
    access_type: "paid",
    // Deliberately left `draft` (see file header) alongside Weekly Founder
    // Review — still being written.
    status: "draft",
    name: "Founder Fit Assessment",
    slug: "founder-fit-assessment",
    short_description: "Assess whether this idea fits your skills, resources and risk appetite before you assess whether the market wants it.",
    full_description: "A candid self-assessment of founder-idea fit: relevant skills, time and money available, and risk appetite, scored against what the idea will actually demand. Still being finalised before publication.",
    outcome_statement: "A documented answer to whether this is the right idea for you specifically to pursue.",
    target_audience: "Founders in the Idea Validation Pack deciding whether to invest further.",
    when_to_use: "Use early, alongside Idea Intake.",
    when_not_to_use: "Not a market-validation tool — it only assesses fit, not demand.",
    completion_minutes_min: 20,
    completion_minutes_max: 30,
    skill_level: "beginner",
    current_version: "0.8",
    price_minor: 900,
    compare_at_price_minor: null,
    currency_code: "GBP",
    featured: false,
    published_at: null,
    scheduled_for: null,
    categories: [catRef("product-strategy")],
    stages: [stageRef("validate")],
    formats: ["markdown"],
    is_placeholder: true,
    framework_id: null,
    tool_key: null,
    licence: standardLicence,
    quality_standard: { purpose: true, instructions: true, thinkingPrompts: true },
    files: [
      { id: "founder-fit-assessment-md", file_role: "template", file_format: "markdown", display_name: "Founder Fit Assessment (Markdown)", is_public_preview: false },
    ],
    seo_title: null,
    seo_description: null,
  },
  {
    id: "problem-evidence-review",
    product_type: "template",
    access_type: "paid",
    status: "unlisted",
    name: "Problem Evidence Review",
    slug: "problem-evidence-review",
    short_description: "Weigh the evidence you have for the problem's existence against the evidence you're assuming.",
    full_description: "Goes further than the free Problem Definition Worksheet: sorts every piece of 'evidence' the team has cited into confirmed, anecdotal, or assumed, and flags where the case for the problem is thinner than it feels.",
    outcome_statement: "An honest evidence rating for the problem, not just a description of it.",
    target_audience: "Teams in the Idea Validation Pack who have completed a problem definition.",
    when_to_use: "Use after the Problem Definition Worksheet, before designing a solution.",
    when_not_to_use: "Not useful before a problem statement exists.",
    completion_minutes_min: 25,
    completion_minutes_max: 35,
    skill_level: "intermediate",
    current_version: "1.0",
    price_minor: 900,
    compare_at_price_minor: null,
    currency_code: "GBP",
    featured: false,
    published_at: "2026-06-18T09:00:00Z",
    scheduled_for: null,
    categories: [catRef("customer-research")],
    stages: [stageRef("idea")],
    formats: ["markdown"],
    is_placeholder: true,
    framework_id: null,
    tool_key: null,
    licence: standardLicence,
    quality_standard: { purpose: true, instructions: true, evidenceFields: true },
    files: [
      { id: "problem-evidence-review-md", file_role: "template", file_format: "markdown", display_name: "Problem Evidence Review (Markdown)", is_public_preview: false },
    ],
    seo_title: null,
    seo_description: null,
  },
  {
    id: "alternatives-and-competitors",
    product_type: "template",
    access_type: "paid",
    status: "unlisted",
    name: "Alternatives and Competitors",
    slug: "alternatives-and-competitors",
    short_description: "A deeper competitive-positioning map, building on the free Existing Alternatives Review.",
    full_description: "Extends the free alternatives review into a full positioning map: direct competitors, adjacent products, manual workarounds and the cost of switching, plotted against the dimensions that matter most to your customer.",
    outcome_statement: "A positioning map showing where your idea sits relative to every real alternative.",
    target_audience: "Teams in the Idea Validation Pack who want a fuller competitive picture.",
    when_to_use: "Use after the problem is defined, before you fix on a solution.",
    when_not_to_use: "Not a substitute for talking to customers about why they haven't switched.",
    completion_minutes_min: 30,
    completion_minutes_max: 45,
    skill_level: "intermediate",
    current_version: "1.0",
    price_minor: 900,
    compare_at_price_minor: null,
    currency_code: "GBP",
    featured: false,
    published_at: "2026-06-19T09:00:00Z",
    scheduled_for: null,
    categories: [catRef("product-strategy")],
    stages: [stageRef("idea")],
    formats: ["markdown"],
    is_placeholder: true,
    framework_id: null,
    tool_key: null,
    licence: standardLicence,
    quality_standard: { purpose: true, instructions: true, evidenceFields: true },
    files: [
      { id: "alternatives-and-competitors-md", file_role: "template", file_format: "markdown", display_name: "Alternatives and Competitors (Markdown)", is_public_preview: false },
    ],
    seo_title: null,
    seo_description: null,
  },
  {
    id: "proven-better-new-assessment-pro",
    product_type: "template",
    access_type: "paid",
    status: "unlisted",
    name: "Copy–Improve–Differentiate Assessment (Pro)",
    slug: "proven-better-new-assessment-pro",
    short_description: "The full Copy–Improve–Differentiate workbook with worked scoring, facilitator notes and a team-workshop edition.",
    full_description: "The paid, deeper edition of the free Copy–Improve–Differentiate Assessment: adds a weighted scoring model, facilitator notes for running the assessment as a team workshop, and worked examples for all three classifications.",
    outcome_statement: "A team-facilitated Copy/Improve/Differentiate verdict with a documented evidence plan.",
    target_audience: "Teams (not solo founders) working through the Idea Validation Pack together.",
    when_to_use: "Use as part of the Idea Validation Pack, in place of the free assessment, when working as a team.",
    when_not_to_use: "If you're working solo, the free Copy–Improve–Differentiate Assessment is enough.",
    completion_minutes_min: 40,
    completion_minutes_max: 60,
    skill_level: "intermediate",
    current_version: "1.0",
    price_minor: 900,
    compare_at_price_minor: null,
    currency_code: "GBP",
    featured: false,
    published_at: "2026-06-19T09:00:00Z",
    scheduled_for: null,
    categories: [catRef("product-strategy")],
    stages: [stageRef("validate")],
    formats: ["markdown", "pdf"],
    is_placeholder: true,
    framework_id: null,
    tool_key: null,
    licence: standardLicence,
    quality_standard: { purpose: true, instructions: true, thinkingPrompts: true, evidenceFields: true, facilitatorEdition: true },
    files: [
      { id: "proven-better-new-assessment-pro-md", file_role: "template", file_format: "markdown", display_name: "Copy–Improve–Differentiate Assessment Pro (Markdown)", is_public_preview: false },
      { id: "proven-better-new-assessment-pro-facilitator", file_role: "facilitator_guide", file_format: "pdf", display_name: "Facilitator guide for team workshops", is_public_preview: false },
    ],
    seo_title: null,
    seo_description: null,
  },
  {
    id: "riskiest-assumptions",
    product_type: "template",
    access_type: "paid",
    status: "unlisted",
    name: "Riskiest Assumptions",
    slug: "riskiest-assumptions",
    short_description: "Rank every assumption behind your idea by impact and uncertainty, then decide which to test first.",
    full_description: "Builds directly on the free Assumption and Evidence Tracker: plots every open assumption on an impact-versus-uncertainty grid so the team can agree, with evidence rather than opinion, which one to test first.",
    outcome_statement: "A ranked shortlist of the 3–5 assumptions worth testing next.",
    target_audience: "Teams in the Idea Validation Pack with an existing assumption log.",
    when_to_use: "Use once you have at least five assumptions logged.",
    when_not_to_use: "Not useful before you've started tracking assumptions at all.",
    completion_minutes_min: 20,
    completion_minutes_max: 30,
    skill_level: "intermediate",
    current_version: "1.0",
    price_minor: 900,
    compare_at_price_minor: null,
    currency_code: "GBP",
    featured: false,
    published_at: "2026-06-20T09:00:00Z",
    scheduled_for: null,
    categories: [catRef("product-strategy")],
    stages: [stageRef("validate")],
    formats: ["markdown"],
    is_placeholder: true,
    framework_id: null,
    tool_key: null,
    licence: standardLicence,
    quality_standard: { purpose: true, instructions: true, evidenceFields: true, decisionOutcome: true },
    files: [
      { id: "riskiest-assumptions-md", file_role: "template", file_format: "markdown", display_name: "Riskiest Assumptions (Markdown)", is_public_preview: false },
    ],
    seo_title: null,
    seo_description: null,
  },
  {
    id: "customer-interview-system",
    product_type: "template",
    access_type: "paid",
    status: "unlisted",
    name: "Customer Interview System",
    slug: "customer-interview-system",
    short_description: "A complete interview system: scheduling scripts, a question bank, and a synthesis method for turning notes into evidence.",
    full_description: "The paid, complete version of the free Customer Interview Planner: adds outreach and scheduling scripts, a larger question bank organised by what you're trying to learn, and a structured method for synthesising raw notes into findings.",
    outcome_statement: "A repeatable interview process from outreach through to written findings.",
    target_audience: "Teams in the Idea Validation Pack planning more than a handful of interviews.",
    when_to_use: "Use once you're ready to run five or more interviews.",
    when_not_to_use: "For one or two casual conversations, the free Customer Interview Planner is enough.",
    completion_minutes_min: 45,
    completion_minutes_max: 90,
    skill_level: "intermediate",
    current_version: "1.0",
    price_minor: 900,
    compare_at_price_minor: null,
    currency_code: "GBP",
    featured: false,
    published_at: "2026-06-20T09:00:00Z",
    scheduled_for: null,
    categories: [catRef("customer-research")],
    stages: [stageRef("validate")],
    formats: ["markdown"],
    is_placeholder: true,
    framework_id: null,
    tool_key: null,
    licence: standardLicence,
    quality_standard: { purpose: true, instructions: true, evidenceFields: true, aiAgentEdition: true },
    files: [
      { id: "customer-interview-system-md", file_role: "template", file_format: "markdown", display_name: "Customer Interview System (Markdown, AI-agent-ready)", is_public_preview: false },
    ],
    seo_title: null,
    seo_description: null,
  },
  {
    id: "evidence-synthesis",
    product_type: "template",
    access_type: "paid",
    status: "unlisted",
    name: "Evidence Synthesis",
    slug: "evidence-synthesis",
    short_description: "Turn a stack of interview notes and evidence into a small number of clear findings.",
    full_description: "Interview fatigue is real: after five or ten conversations, most teams have pages of notes and no clarity. This template forces a synthesis pass — grouping evidence into themes, rating confidence per theme, and stating the finding in one sentence each.",
    outcome_statement: "A short, ranked list of findings, each backed by cited evidence.",
    target_audience: "Teams who've completed a round of interviews using the Customer Interview System.",
    when_to_use: "Use immediately after finishing a round of interviews, while the notes are fresh.",
    when_not_to_use: "Not useful with fewer than three interviews' worth of notes.",
    completion_minutes_min: 30,
    completion_minutes_max: 60,
    skill_level: "intermediate",
    current_version: "1.0",
    price_minor: 900,
    compare_at_price_minor: null,
    currency_code: "GBP",
    featured: false,
    published_at: "2026-06-20T09:00:00Z",
    scheduled_for: null,
    categories: [catRef("customer-research")],
    stages: [stageRef("validate")],
    formats: ["markdown"],
    is_placeholder: true,
    framework_id: null,
    tool_key: null,
    licence: standardLicence,
    quality_standard: { purpose: true, instructions: true, evidenceFields: true, decisionOutcome: true },
    files: [
      { id: "evidence-synthesis-md", file_role: "template", file_format: "markdown", display_name: "Evidence Synthesis (Markdown)", is_public_preview: false },
    ],
    seo_title: null,
    seo_description: null,
  },
  {
    id: "proceed-revise-pause-decision",
    product_type: "template",
    access_type: "paid",
    status: "unlisted",
    name: "Proceed–Revise–Pause Decision",
    slug: "proceed-revise-pause-decision",
    short_description: "The closing decision template: proceed, revise or pause, with the reasoning documented for future reference.",
    full_description: "The final step of the Idea Validation Pack. Pulls together the Copy/Improve/Differentiate verdict, the assumption log and the evidence synthesis into a single documented decision — proceed, revise, or pause — with the reasoning recorded so it can be revisited later.",
    outcome_statement: "A written, evidence-backed proceed/revise/pause decision with a clear next action.",
    target_audience: "Teams finishing the Idea Validation Pack.",
    when_to_use: "Use as the last step, once evidence synthesis is complete.",
    when_not_to_use: "Not useful without the evidence gathered in the earlier pack steps.",
    completion_minutes_min: 20,
    completion_minutes_max: 30,
    skill_level: "intermediate",
    current_version: "1.0",
    price_minor: 900,
    compare_at_price_minor: null,
    currency_code: "GBP",
    featured: false,
    published_at: "2026-06-20T09:00:00Z",
    scheduled_for: null,
    categories: [catRef("product-strategy")],
    // v3 journey remap exception: this product's own content ("proceed, revise or
    // pause, with reasoning documented") is a decision output, not an idea
    // evaluation -- the otherwise-uniform evaluate-an-idea -> validate remap doesn't
    // fit here.
    stages: [stageRef("decide")],
    formats: ["markdown"],
    is_placeholder: true,
    framework_id: null,
    tool_key: null,
    licence: standardLicence,
    quality_standard: { purpose: true, instructions: true, decisionOutcome: true, nextStep: true, reviewDate: true },
    files: [
      { id: "proceed-revise-pause-decision-md", file_role: "template", file_format: "markdown", display_name: "Proceed–Revise–Pause Decision (Markdown)", is_public_preview: false },
    ],
    seo_title: null,
    seo_description: null,
  },
];

// ---------------------------------------------------------------------------
// Product Definition Pack — 9 bundle items (spec §37)
// ---------------------------------------------------------------------------

const productDefinitionItems: Product[] = [
  {
    id: "product-vision",
    product_type: "template",
    access_type: "paid",
    status: "unlisted",
    name: "Product Vision",
    slug: "product-vision",
    short_description: "A one-page vision statement that explains where the product is going and why it matters.",
    full_description: "A short, opinionated vision statement — not a mission-statement generator. Names the change you want to see in the customer's world and why your product is the way to get there.",
    outcome_statement: "A one-page vision statement the whole team can repeat from memory.",
    target_audience: "Teams starting the Product Definition Pack after idea validation.",
    when_to_use: "Use as the first step in defining the product.",
    when_not_to_use: "Not useful before the idea has been validated — start with the Idea Validation Pack.",
    completion_minutes_min: 20,
    completion_minutes_max: 30,
    skill_level: "beginner",
    current_version: "1.0",
    price_minor: 1100,
    compare_at_price_minor: null,
    currency_code: "GBP",
    featured: false,
    published_at: "2026-07-01T09:00:00Z",
    scheduled_for: null,
    categories: [catRef("product-development")],
    stages: [stageRef("design")],
    formats: ["markdown"],
    is_placeholder: true,
    framework_id: null,
    tool_key: null,
    licence: standardLicence,
    quality_standard: { purpose: true, instructions: true, decisionOutcome: true },
    files: [
      { id: "product-vision-md", file_role: "template", file_format: "markdown", display_name: "Product Vision (Markdown)", is_public_preview: false },
    ],
    seo_title: null,
    seo_description: null,
  },
  {
    id: "target-user-definition",
    product_type: "template",
    access_type: "paid",
    status: "unlisted",
    name: "Target User Definition",
    slug: "target-user-definition",
    short_description: "Define your target user precisely enough that 'for everyone' is no longer an acceptable answer.",
    full_description: "Replaces vague personas with a specific definition: who the product is for right now, who it is explicitly not for yet, and how you'll recognise a target user when you meet one.",
    outcome_statement: "A specific, falsifiable definition of who the product is for.",
    target_audience: "Teams in the Product Definition Pack scoping their initial audience.",
    when_to_use: "Use after the Product Vision, before writing user needs.",
    when_not_to_use: "Not useful if you intend to serve every possible customer segment from day one.",
    completion_minutes_min: 25,
    completion_minutes_max: 35,
    skill_level: "beginner",
    current_version: "1.0",
    price_minor: 1100,
    compare_at_price_minor: null,
    currency_code: "GBP",
    featured: false,
    published_at: "2026-07-01T09:00:00Z",
    scheduled_for: null,
    categories: [catRef("product-development")],
    stages: [stageRef("design")],
    formats: ["markdown"],
    is_placeholder: true,
    framework_id: null,
    tool_key: null,
    licence: standardLicence,
    quality_standard: { purpose: true, instructions: true, thinkingPrompts: true },
    files: [
      { id: "target-user-definition-md", file_role: "template", file_format: "markdown", display_name: "Target User Definition (Markdown)", is_public_preview: false },
    ],
    seo_title: null,
    seo_description: null,
  },
  {
    id: "user-needs-and-scenarios",
    product_type: "template",
    access_type: "paid",
    status: "unlisted",
    name: "User Needs and Scenarios",
    slug: "user-needs-and-scenarios",
    short_description: "Document the needs and real-world scenarios your product must handle.",
    full_description: "A structured way to capture user needs as scenarios — situation, goal and desired outcome — rather than a flat feature wishlist, so the team is designing for real moments rather than abstractions.",
    outcome_statement: "A short set of scenarios the product must handle well.",
    target_audience: "Teams in the Product Definition Pack, after defining the target user.",
    when_to_use: "Use after Target User Definition, before Product Principles.",
    when_not_to_use: "Not a replacement for direct customer research if none has been done yet.",
    completion_minutes_min: 30,
    completion_minutes_max: 45,
    skill_level: "intermediate",
    current_version: "1.0",
    price_minor: 1100,
    compare_at_price_minor: null,
    currency_code: "GBP",
    featured: false,
    published_at: "2026-07-02T09:00:00Z",
    scheduled_for: null,
    categories: [catRef("product-development")],
    stages: [stageRef("design")],
    formats: ["markdown"],
    is_placeholder: true,
    framework_id: null,
    tool_key: null,
    licence: standardLicence,
    quality_standard: { purpose: true, instructions: true, evidenceFields: true },
    files: [
      { id: "user-needs-and-scenarios-md", file_role: "template", file_format: "markdown", display_name: "User Needs and Scenarios (Markdown)", is_public_preview: false },
    ],
    seo_title: null,
    seo_description: null,
  },
  {
    id: "product-principles",
    product_type: "template",
    access_type: "paid",
    status: "unlisted",
    name: "Product Principles",
    slug: "product-principles",
    short_description: "Write the small set of principles that will resolve disagreements when priorities conflict.",
    full_description: "A short worksheet for writing 3–5 product principles — the kind that actually change a decision, not generic values statements. Used later by the Feature Evaluation template to score candidate features.",
    outcome_statement: "3–5 written product principles the team can cite when priorities conflict.",
    target_audience: "Teams in the Product Definition Pack about to start prioritising features.",
    when_to_use: "Use after User Needs and Scenarios, before Feature Evaluation.",
    when_not_to_use: "Not useful as a branding or marketing exercise — these are internal decision principles.",
    completion_minutes_min: 25,
    completion_minutes_max: 40,
    skill_level: "intermediate",
    current_version: "1.0",
    price_minor: 1100,
    compare_at_price_minor: null,
    currency_code: "GBP",
    featured: false,
    published_at: "2026-07-02T09:00:00Z",
    scheduled_for: null,
    categories: [catRef("product-development")],
    stages: [stageRef("design")],
    formats: ["markdown"],
    is_placeholder: true,
    framework_id: null,
    tool_key: null,
    licence: standardLicence,
    quality_standard: { purpose: true, instructions: true, decisionOutcome: true },
    files: [
      { id: "product-principles-md", file_role: "template", file_format: "markdown", display_name: "Product Principles (Markdown)", is_public_preview: false },
    ],
    seo_title: null,
    seo_description: null,
  },
  {
    id: "feature-evaluation",
    product_type: "template",
    access_type: "paid",
    status: "unlisted",
    name: "Feature Evaluation",
    slug: "feature-evaluation",
    short_description: "Score candidate features against your product principles and user needs before committing to build them.",
    full_description: "A scoring worksheet that weighs each candidate feature against the product principles and documented user needs, producing a ranked shortlist instead of a debate settled by whoever spoke last.",
    outcome_statement: "A ranked shortlist of features with the reasoning for each score recorded.",
    target_audience: "Teams in the Product Definition Pack with a features backlog to prioritise.",
    when_to_use: "Use once Product Principles and User Needs and Scenarios are complete.",
    when_not_to_use: "Not useful without documented principles to score against.",
    completion_minutes_min: 30,
    completion_minutes_max: 60,
    skill_level: "intermediate",
    current_version: "1.0",
    price_minor: 1100,
    compare_at_price_minor: null,
    currency_code: "GBP",
    featured: false,
    published_at: "2026-07-03T09:00:00Z",
    scheduled_for: null,
    categories: [catRef("product-development")],
    stages: [stageRef("design")],
    formats: ["markdown"],
    is_placeholder: true,
    framework_id: null,
    tool_key: null,
    licence: standardLicence,
    quality_standard: { purpose: true, instructions: true, decisionOutcome: true },
    files: [
      { id: "feature-evaluation-md", file_role: "template", file_format: "markdown", display_name: "Feature Evaluation (Markdown)", is_public_preview: false },
    ],
    seo_title: null,
    seo_description: null,
  },
  {
    id: "mvp-scope",
    product_type: "template",
    access_type: "paid",
    status: "unlisted",
    name: "MVP Scope",
    slug: "mvp-scope",
    short_description: "The full MVP scoping template with a cut-line exercise for deciding what ships first.",
    full_description: "A fuller version of the free MVP Scope in One Page, with a cut-line exercise: rank every feature by whether the MVP fails without it, then draw the line where the evidence — not the enthusiasm — runs out.",
    outcome_statement: "A defined MVP scope with an explicit, defensible cut line.",
    target_audience: "Teams in the Product Definition Pack ready to scope a first release.",
    when_to_use: "Use after Feature Evaluation, before Product Specification.",
    when_not_to_use: "For a very small first release, the free MVP Scope in One Page may be enough.",
    completion_minutes_min: 30,
    completion_minutes_max: 45,
    skill_level: "intermediate",
    current_version: "1.0",
    price_minor: 1100,
    compare_at_price_minor: null,
    currency_code: "GBP",
    featured: false,
    published_at: "2026-07-03T09:00:00Z",
    scheduled_for: null,
    categories: [catRef("product-development")],
    stages: [stageRef("build")],
    formats: ["markdown"],
    is_placeholder: true,
    framework_id: null,
    tool_key: null,
    licence: standardLicence,
    quality_standard: { purpose: true, instructions: true, decisionOutcome: true, nextStep: true },
    files: [
      { id: "mvp-scope-md", file_role: "template", file_format: "markdown", display_name: "MVP Scope (Markdown)", is_public_preview: false },
    ],
    seo_title: null,
    seo_description: null,
  },
  {
    id: "product-specification",
    product_type: "template",
    access_type: "paid",
    status: "unlisted",
    name: "Product Specification",
    slug: "product-specification",
    short_description: "A specification template an engineer or an AI agent can build from without guessing.",
    full_description: "Structured so that ambiguity is visible rather than hidden: required inputs, explicit non-goals, and a section for information the reader (human or AI agent) must not invent. Follows the AI-agent-ready structure described in the spec's Markdown format guidance.",
    outcome_statement: "A specification detailed enough to hand to an engineer, contractor or AI agent.",
    target_audience: "Teams and solo founders in the Product Definition Pack ready to brief development.",
    when_to_use: "Use once MVP Scope is finalised, before development starts.",
    when_not_to_use: "Not useful while scope is still actively changing week to week.",
    completion_minutes_min: 60,
    completion_minutes_max: 120,
    skill_level: "intermediate",
    current_version: "1.0",
    price_minor: 1100,
    compare_at_price_minor: null,
    currency_code: "GBP",
    featured: false,
    published_at: "2026-07-04T09:00:00Z",
    scheduled_for: null,
    categories: [catRef("product-development")],
    stages: [stageRef("design")],
    formats: ["markdown"],
    is_placeholder: true,
    framework_id: null,
    tool_key: null,
    licence: standardLicence,
    quality_standard: { purpose: true, inputs: true, instructions: true, decisionOutcome: true, aiAgentEdition: true },
    files: [
      { id: "product-specification-md", file_role: "template", file_format: "markdown", display_name: "Product Specification (Markdown, AI-agent-ready)", is_public_preview: false },
    ],
    seo_title: null,
    seo_description: null,
  },
  {
    id: "acceptance-criteria",
    product_type: "template",
    access_type: "paid",
    status: "unlisted",
    name: "Acceptance Criteria",
    slug: "acceptance-criteria",
    short_description: "Write acceptance criteria that make 'done' an objective, testable fact.",
    full_description: "A worksheet for turning each item in the Product Specification into testable, unambiguous acceptance criteria, so 'is this done' never becomes a matter of opinion.",
    outcome_statement: "Testable acceptance criteria attached to every item in the specification.",
    target_audience: "Teams in the Product Definition Pack finalising the specification.",
    when_to_use: "Use directly after the Product Specification.",
    when_not_to_use: "Not useful before the specification itself is written.",
    completion_minutes_min: 30,
    completion_minutes_max: 60,
    skill_level: "intermediate",
    current_version: "1.0",
    price_minor: 1100,
    compare_at_price_minor: null,
    currency_code: "GBP",
    featured: false,
    published_at: "2026-07-04T09:00:00Z",
    scheduled_for: null,
    categories: [catRef("product-development")],
    stages: [stageRef("design")],
    formats: ["markdown"],
    is_placeholder: true,
    framework_id: null,
    tool_key: null,
    licence: standardLicence,
    quality_standard: { purpose: true, instructions: true, decisionOutcome: true },
    files: [
      { id: "acceptance-criteria-md", file_role: "template", file_format: "markdown", display_name: "Acceptance Criteria (Markdown)", is_public_preview: false },
    ],
    seo_title: null,
    seo_description: null,
  },
  {
    id: "launch-readiness-review",
    product_type: "template",
    access_type: "paid",
    status: "unlisted",
    name: "Launch Readiness Review",
    slug: "launch-readiness-review",
    short_description: "A pre-launch checklist covering product, support and go-to-market readiness.",
    full_description: "A closing checklist for the Product Definition Pack: confirms the product, support process and go-to-market plan are genuinely ready before launch, not just that a deadline has arrived.",
    outcome_statement: "A completed readiness review with any open risks explicitly documented.",
    target_audience: "Teams in the Product Definition Pack approaching launch.",
    when_to_use: "Use in the final week before a planned launch.",
    when_not_to_use: "Not useful more than a few weeks before launch — readiness changes fast.",
    completion_minutes_min: 30,
    completion_minutes_max: 45,
    skill_level: "intermediate",
    current_version: "1.0",
    price_minor: 1100,
    compare_at_price_minor: null,
    currency_code: "GBP",
    featured: false,
    published_at: "2026-07-05T09:00:00Z",
    scheduled_for: null,
    categories: [catRef("go-to-market")],
    stages: [stageRef("launch")],
    formats: ["markdown"],
    is_placeholder: true,
    framework_id: null,
    tool_key: null,
    licence: standardLicence,
    quality_standard: { purpose: true, instructions: true, decisionOutcome: true, nextStep: true },
    files: [
      { id: "launch-readiness-review-md", file_role: "template", file_format: "markdown", display_name: "Launch Readiness Review (Markdown)", is_public_preview: false },
    ],
    seo_title: null,
    seo_description: null,
  },
];

// ---------------------------------------------------------------------------
// Product Idea Assessor family outputs (spec v3 §14.7, §39.3) — the Guide and
// Tool that, together with the existing `proven-better-new-assessment`
// Template above (reassigned to this framework), complete the flagship
// family's Guide -> Template -> Tool set. The Guide's body lives in
// content/guides/product-idea-assessor.mdx; this row is metadata joined to
// that file by matching slug (spec §2.9's hybrid content model — no separate
// content_path field needed while there's exactly one join key).
// ---------------------------------------------------------------------------

const productIdeaAssessorFamilyOutputs: Product[] = [
  {
    id: "product-idea-assessor-guide",
    product_type: "guide",
    access_type: "free",
    status: "published",
    name: "Product Idea Assessor: the Guide",
    slug: "product-idea-assessor",
    short_description:
      "How to classify an idea as Copy, Improve or Differentiate, and why that classification should decide how much evidence you gather next.",
    full_description:
      "Explains the Copy–Improve–Differentiate method end to end, with the reasoning behind each category and the single most useful test for each. Read this before using the Template or the Tool — both assume you understand the classification this guide teaches.",
    outcome_statement: "Understand which of the three categories your idea falls into, and why that changes how much evidence you need.",
    target_audience: "Founders and product people who want to understand the method before applying it.",
    when_to_use: "Read this first, before the Template or the Tool.",
    when_not_to_use: "Skip straight to the Tool if you already understand Copy/Improve/Differentiate and just want a scored result.",
    completion_minutes_min: 8,
    completion_minutes_max: 12,
    skill_level: "beginner",
    current_version: "1.0",
    price_minor: null,
    compare_at_price_minor: null,
    currency_code: "GBP",
    featured: true,
    published_at: "2026-08-01T09:00:00Z",
    scheduled_for: null,
    categories: [catRef("product-strategy")],
    stages: [stageRef("validate")],
    formats: [],
    is_placeholder: true,
    framework_id: PRODUCT_IDEA_ASSESSOR_FRAMEWORK_ID,
    tool_key: null,
    licence: null,
    quality_standard: { purpose: true, instructions: true, thinkingPrompts: true, nextStep: true },
    files: [],
    seo_title: "Product Idea Assessor guide — the Copy–Improve–Differentiate method",
    seo_description:
      "How to classify an idea as Copy, Improve or Differentiate, and why that classification should decide how much evidence you gather next.",
  },
  {
    id: "product-idea-assessor-tool",
    product_type: "tool",
    access_type: "free",
    status: "published",
    name: "Product Idea Assessor",
    slug: "product-idea-assessor-tool",
    short_description:
      "Answer a few questions about your idea and get a scored evidence-quality readiness verdict — proceed, gather more evidence, or pause.",
    full_description:
      "The interactive version of the Copy–Improve–Differentiate Assessment. Classify your idea, answer four evidence questions, and get a deterministic score, a named strongest and weakest area, and one concrete next evidence action — usable anonymously, with no account required.",
    outcome_statement: "A scored readiness verdict — ready to proceed, gather more evidence, or high risk — plus one clear next action.",
    target_audience: "Founders who want an immediate, structured read on a specific idea.",
    when_to_use: "Use once you can state the idea in a sentence and have some evidence to answer honestly.",
    when_not_to_use: "Not a substitute for the underlying customer evidence — it scores the evidence you already have, it doesn't gather it for you.",
    completion_minutes_min: 5,
    completion_minutes_max: 10,
    skill_level: "beginner",
    current_version: "1.0",
    price_minor: null,
    compare_at_price_minor: null,
    currency_code: "GBP",
    featured: true,
    published_at: "2026-08-01T09:00:00Z",
    scheduled_for: null,
    categories: [catRef("product-strategy")],
    stages: [stageRef("validate")],
    formats: [],
    is_placeholder: true,
    framework_id: PRODUCT_IDEA_ASSESSOR_FRAMEWORK_ID,
    tool_key: "product-idea-assessor",
    licence: null,
    quality_standard: { purpose: true, inputs: true, decisionOutcome: true, nextStep: true },
    files: [],
    seo_title: "Product Idea Assessor — free interactive idea assessment tool",
    seo_description:
      "Answer a few questions and get a scored, evidence-based readiness verdict on your product idea, free, no account required.",
  },
];

// ---------------------------------------------------------------------------
// Customer Discovery Kit family outputs (spec v3 §14.7, §37) — the Guide and
// Tool that, together with the existing `customer-interview-planner` and
// `assumption-and-evidence-tracker` Templates above (reassigned to this
// framework), complete the family's Guide -> Template -> Tool set. See
// docs/decisions/0021 for why this family reused existing v2-era template
// and guide content rather than writing new templates from scratch. The
// Guide's body lives in content/guides/customer-discovery-kit.mdx; this row
// is metadata joined to that file by matching slug.
// ---------------------------------------------------------------------------

const customerDiscoveryKitFamilyOutputs: Product[] = [
  {
    id: "customer-discovery-kit-guide",
    product_type: "guide",
    access_type: "free",
    status: "published",
    name: "Customer Discovery Kit: the Guide",
    slug: "customer-discovery-kit",
    short_description: "How to plan and run customer interviews that produce real evidence, and know when you've gathered enough of it.",
    full_description:
      "Explains how to plan who to talk to, run interviews that avoid leading questions and premature pitching, log evidence separately from assumptions, and recognise when a real pattern has formed. Read this before the Template or the Tool — both assume the technique this guide teaches.",
    outcome_statement: "A repeatable way to run customer interviews that can actually change your mind, and know when you've heard enough.",
    target_audience: "Founders and product people about to run their first — or next — round of customer discovery.",
    when_to_use: "Read this first, before the Template or the Tool.",
    when_not_to_use: "Skip straight to the Tool if you've already run your interviews and just want to score the evidence you gathered.",
    completion_minutes_min: 8,
    completion_minutes_max: 12,
    skill_level: "beginner",
    current_version: "1.0",
    price_minor: null,
    compare_at_price_minor: null,
    currency_code: "GBP",
    featured: true,
    published_at: "2026-08-09T09:00:00Z",
    scheduled_for: null,
    categories: [catRef("customer-research")],
    stages: [stageRef("validate")],
    formats: [],
    is_placeholder: true,
    framework_id: CUSTOMER_DISCOVERY_KIT_FRAMEWORK_ID,
    tool_key: null,
    licence: null,
    quality_standard: { purpose: true, instructions: true, thinkingPrompts: true, nextStep: true },
    files: [],
    seo_title: "Customer Discovery Kit guide — run interviews that produce real evidence",
    seo_description:
      "How to plan and run customer interviews that avoid leading questions, log evidence separately from assumptions, and know when you've heard enough.",
  },
  {
    id: "customer-discovery-kit-tool",
    product_type: "tool",
    access_type: "free",
    status: "published",
    name: "Evidence Analyser",
    slug: "customer-discovery-kit-tool",
    short_description: "Score how strong your customer-discovery evidence actually is, and whether leading questions mean you can't trust the pattern yet.",
    full_description:
      "Answer five questions about the interviews you've already run — how many, how open your questions were, what kind of evidence you heard, whether anyone showed real commitment, and how consistent the pattern is — and get a deterministic evidence-strength score, a bias-risk flag, and one concrete next action. Usable anonymously, with no account required.",
    outcome_statement: "An evidence-strength score, a bias-risk flag, and one clear next action.",
    target_audience: "Founders who've run some customer interviews and want a structured read on whether the evidence actually holds up.",
    when_to_use: "Use after a first round of interviews, before you treat what you heard as a settled pattern.",
    when_not_to_use: "Not a substitute for running the interviews — it scores evidence you already have, it doesn't gather it for you.",
    completion_minutes_min: 5,
    completion_minutes_max: 10,
    skill_level: "beginner",
    current_version: "1.0",
    price_minor: null,
    compare_at_price_minor: null,
    currency_code: "GBP",
    featured: true,
    published_at: "2026-08-09T09:00:00Z",
    scheduled_for: null,
    categories: [catRef("customer-research")],
    stages: [stageRef("validate")],
    formats: [],
    is_placeholder: true,
    framework_id: CUSTOMER_DISCOVERY_KIT_FRAMEWORK_ID,
    tool_key: "customer-discovery-kit",
    licence: null,
    quality_standard: { purpose: true, inputs: true, decisionOutcome: true, nextStep: true },
    files: [],
    seo_title: "Evidence Analyser — free customer-discovery evidence scoring tool",
    seo_description: "Score how strong your customer-interview evidence actually is, free, no account required.",
  },
];

// ---------------------------------------------------------------------------
// Better Decision Maker family outputs (spec v3 §14.7, §37) — Guide, Template
// and Tool all newly written for this family (unlike Customer Discovery Kit,
// there was no existing v2-era content to reuse — see docs/decisions/0022).
// The Guide's body lives in content/guides/better-decision-maker.mdx, joined
// to this row by matching slug; the Template's body lives in
// content/seed/free-files/decision-worksheet.md.
// ---------------------------------------------------------------------------

const betterDecisionMakerFamilyOutputs: Product[] = [
  {
    id: "better-decision-maker-guide",
    product_type: "guide",
    access_type: "free",
    status: "published",
    name: "Better Decision Maker: the Guide",
    slug: "better-decision-maker",
    short_description: "Four techniques for deciding under uncertainty: reversibility, inversion, simple rules and expected value.",
    full_description:
      "Explains how to classify a decision by reversibility, invert the question to find what would guarantee failure, check it against your simple rules, and estimate expected value when you have real options to compare. Read this before the Template or the Tool — both assume the technique this guide teaches.",
    outcome_statement: "A repeatable way to decide under uncertainty without waiting for certainty that never arrives.",
    target_audience: "Founders facing an important decision under uncertainty.",
    when_to_use: "Read this first, before the Template or the Tool.",
    when_not_to_use: "Skip straight to the Tool if you already have two options in mind and just want a scored comparison.",
    completion_minutes_min: 8,
    completion_minutes_max: 12,
    skill_level: "beginner",
    current_version: "1.0",
    price_minor: null,
    compare_at_price_minor: null,
    currency_code: "GBP",
    featured: true,
    published_at: "2026-08-09T09:00:00Z",
    scheduled_for: null,
    categories: [catRef("product-strategy")],
    stages: [stageRef("decide")],
    formats: [],
    is_placeholder: true,
    framework_id: BETTER_DECISION_MAKER_FRAMEWORK_ID,
    tool_key: null,
    licence: null,
    quality_standard: { purpose: true, instructions: true, thinkingPrompts: true, nextStep: true },
    files: [],
    seo_title: "Better Decision Maker guide — decide under uncertainty without waiting for certainty",
    seo_description:
      "Four techniques for making an important founder decision: reversibility, inversion, simple rules and expected value.",
  },
  {
    id: "decision-worksheet",
    product_type: "template",
    access_type: "free",
    status: "published",
    name: "Decision Worksheet",
    slug: "decision-worksheet",
    short_description: "Work through reversibility, inversion, your simple rules and an expected-value estimate for a decision you're facing.",
    full_description:
      "A structured worksheet covering all four Better Decision Maker techniques for a single decision: classify it by reversibility, invert the question to find what would guarantee failure, check it against your simple rules, and estimate expected value if you have real options to compare. Ends with a documented decision and reasoning you can revisit later.",
    outcome_statement: "A documented decision, reasoned through rather than made on instinct alone.",
    target_audience: "Founders facing an important decision under uncertainty.",
    when_to_use: "Use once you have real options to weigh — after the evidence-gathering stages, not instead of them.",
    when_not_to_use:
      "Not useful for decisions that are genuinely reversible and low-stakes — the process itself costs more time than a quick two-way-door decision deserves.",
    completion_minutes_min: 20,
    completion_minutes_max: 30,
    skill_level: "beginner",
    current_version: "1.0",
    price_minor: null,
    compare_at_price_minor: null,
    currency_code: "GBP",
    featured: true,
    published_at: "2026-08-09T09:00:00Z",
    scheduled_for: null,
    categories: [catRef("product-strategy")],
    stages: [stageRef("decide")],
    formats: ["markdown"],
    is_placeholder: true,
    framework_id: BETTER_DECISION_MAKER_FRAMEWORK_ID,
    tool_key: null,
    licence: standardLicence,
    quality_standard: {
      purpose: true,
      instructions: true,
      thinkingPrompts: true,
      evidenceFields: true,
      decisionOutcome: true,
      nextStep: true,
    },
    files: [
      {
        id: "decision-worksheet-md",
        file_role: "template",
        file_format: "markdown",
        display_name: "Decision Worksheet (Markdown, AI-agent-ready)",
        is_public_preview: false,
      },
    ],
    seo_title: "Decision Worksheet — free template for deciding under uncertainty",
    seo_description: "Work through reversibility, inversion, your simple rules and an expected-value estimate for a decision you're facing, free.",
  },
  {
    id: "better-decision-maker-tool",
    product_type: "tool",
    access_type: "free",
    status: "published",
    name: "Expected Value Comparator",
    slug: "better-decision-maker-tool",
    short_description: "Compare two options by expected value and get a reversibility-aware recommendation.",
    full_description:
      "Answer four questions about each of two options — likelihood of success, impact if it works, effort to attempt, and whether it's a one-way or two-way door — and get an expected-value score for each, a recommendation, a confidence read on how clear the gap is, and one next step. Usable anonymously, with no account required.",
    outcome_statement: "An expected-value comparison of two options, a recommendation, and one clear next step.",
    target_audience: "Founders comparing two real options and wanting a structured, deterministic read on which one to take.",
    when_to_use: "Use once you've narrowed a decision down to two real options worth comparing.",
    when_not_to_use: "Not useful for more than two options at once, or for decisions that don't have distinct alternatives to compare.",
    completion_minutes_min: 5,
    completion_minutes_max: 10,
    skill_level: "beginner",
    current_version: "1.0",
    price_minor: null,
    compare_at_price_minor: null,
    currency_code: "GBP",
    featured: true,
    published_at: "2026-08-09T09:00:00Z",
    scheduled_for: null,
    categories: [catRef("product-strategy")],
    stages: [stageRef("decide")],
    formats: [],
    is_placeholder: true,
    framework_id: BETTER_DECISION_MAKER_FRAMEWORK_ID,
    tool_key: "better-decision-maker",
    licence: null,
    quality_standard: { purpose: true, inputs: true, decisionOutcome: true, nextStep: true },
    files: [],
    seo_title: "Expected Value Comparator — free decision-comparison tool",
    seo_description: "Compare two options by expected value and get a reversibility-aware recommendation, free, no account required.",
  },
];

export const products: Product[] = [
  ...freeProducts,
  ...ideaValidationItems,
  ...productDefinitionItems,
  ...productIdeaAssessorFamilyOutputs,
  ...customerDiscoveryKitFamilyOutputs,
  ...betterDecisionMakerFamilyOutputs,
];

// ---------------------------------------------------------------------------
// Bundles (spec §37 — 2 paid bundles, 9 items each)
// ---------------------------------------------------------------------------

function bundleItemsFrom(items: Product[]): BundleItem[] {
  return items.map((product, index) => ({
    product: toSummary(product),
    is_required: true,
    display_order: index,
  }));
}

export const bundles: Bundle[] = [
  {
    id: "idea-validation-pack",
    product_type: "bundle",
    access_type: "paid",
    status: "published",
    name: "Idea Validation Pack",
    slug: "idea-validation-pack",
    short_description:
      "Nine templates that take you from a raw idea to a documented proceed-revise-pause decision, backed by evidence rather than confidence.",
    full_description:
      "The Idea Validation Pack is the complete evidence-led path from a raw idea to a defensible decision. It sequences nine templates — intake, founder fit, problem evidence, competitive alternatives, a team Copy–Improve–Differentiate workshop, assumption ranking, a full interview system, evidence synthesis, and a closing proceed/revise/pause decision — into a single 1–2 week process, instead of leaving you to assemble one from separate free worksheets.",
    outcome_statement:
      "A documented, evidence-based decision on whether to proceed, revise or pause — not just a folder of worksheets.",
    target_audience: "Founders who want a structured, complete path through idea validation rather than assembling their own process from free templates.",
    when_to_use: "Use end-to-end over 1–2 weeks when you're serious about validating a new idea before committing real time or money.",
    when_not_to_use: "If you only need one part of the process — for example, just customer interviews — the free Customer Interview Planner may be enough on its own.",
    completion_minutes_min: 240,
    completion_minutes_max: 480,
    skill_level: "intermediate",
    current_version: "1.0",
    price_minor: 3900,
    compare_at_price_minor: 8100,
    currency_code: "GBP",
    featured: true,
    published_at: "2026-06-22T09:00:00Z",
    scheduled_for: null,
    categories: [catRef("product-strategy")],
    stages: [stageRef("validate")],
    formats: ["markdown", "pdf"],
    is_placeholder: true,
    framework_id: null,
    tool_key: null,
    licence: standardLicence,
    quality_standard: {
      purpose: true,
      inputs: true,
      instructions: true,
      thinkingPrompts: true,
      evidenceFields: true,
      decisionOutcome: true,
      nextStep: true,
      aiAgentEdition: true,
    },
    files: [
      {
        id: "idea-validation-pack-overview",
        file_role: "instructions",
        file_format: "markdown",
        display_name: "Pack overview and recommended order",
        is_public_preview: true,
      },
    ],
    seo_title: "Idea Validation Pack — 9-template bundle",
    seo_description:
      "Nine templates that take a raw idea to a documented proceed, revise or pause decision, backed by evidence.",
    bundle_items: bundleItemsFrom(ideaValidationItems),
  },
  {
    id: "product-definition-pack",
    product_type: "bundle",
    access_type: "paid",
    status: "published",
    name: "Product Definition Pack",
    slug: "product-definition-pack",
    short_description:
      "Nine templates that take a validated idea to a written product specification ready for design or build.",
    full_description:
      "The Product Definition Pack sequences nine templates — vision, target user, user needs and scenarios, product principles, feature evaluation, MVP scope, a full product specification, acceptance criteria, and a launch readiness review — into one connected process for turning a validated idea into a specification you can actually hand to a builder.",
    outcome_statement:
      "A complete, reviewable product definition: vision, users, scope and acceptance criteria in one connected set.",
    target_audience: "Founders and product managers defining a product after idea validation, before development starts.",
    when_to_use: "Use once you have evidence an idea is worth pursuing and need to define exactly what to build.",
    when_not_to_use: "If you haven't validated the idea yet, start with the Idea Validation Pack first.",
    completion_minutes_min: 300,
    completion_minutes_max: 600,
    skill_level: "intermediate",
    current_version: "1.0",
    price_minor: 4900,
    compare_at_price_minor: 9900,
    currency_code: "GBP",
    featured: false,
    published_at: "2026-07-06T09:00:00Z",
    scheduled_for: null,
    categories: [catRef("product-development")],
    stages: [stageRef("design")],
    formats: ["markdown"],
    is_placeholder: true,
    framework_id: null,
    tool_key: null,
    licence: standardLicence,
    quality_standard: {
      purpose: true,
      inputs: true,
      instructions: true,
      evidenceFields: true,
      decisionOutcome: true,
      nextStep: true,
      aiAgentEdition: true,
    },
    files: [
      {
        id: "product-definition-pack-overview",
        file_role: "instructions",
        file_format: "markdown",
        display_name: "Pack overview and recommended order",
        is_public_preview: true,
      },
    ],
    seo_title: "Product Definition Pack — 9-template bundle",
    seo_description:
      "Nine templates that take a validated idea to a written product specification ready for design or build.",
    bundle_items: bundleItemsFrom(productDefinitionItems),
  },
];

export const catalogue = { products, bundles, categories, stages, licences, frameworks };

export default catalogue;
