/**
 * Reads content/seed/catalogue.ts (the single source of truth for local
 * fixture content) and writes supabase/seed.sql — plain SQL insert
 * statements matching spec §14's column names for it_categories, it_stages,
 * it_licences, it_frameworks, it_products, it_product_categories and
 * it_product_stages. This keeps what the app renders locally (via
 * FixtureCatalogueSource) and what would get pushed to a real Supabase
 * project in sync, with one file as the source of truth rather than
 * maintaining both by hand.
 *
 * Deliberately does NOT insert into it_product_versions, it_files or
 * it_bundle_items (not listed in the build plan's §8 scope for this
 * script) — those need real Storage-backed file rows and version records
 * that don't exist as fixture data in a form this script can safely turn
 * into SQL yet.
 *
 * Idempotent by design: every row-table insert uses `on conflict (id) do
 * update`, since ids are deterministic from slugs (see deterministic-uuid),
 * so re-running this against a database that already has some or all of
 * this data updates it to match the current fixture rather than erroring on
 * duplicate keys. The two join tables (it_product_categories,
 * it_product_stages) don't have a natural per-row id to conflict on, and a
 * product's category/stage set can shrink or change entirely between runs
 * (e.g. the v3 journey-stage remap) — so those sections delete every
 * existing row for the products this script manages before re-inserting,
 * making them an authoritative full replace rather than an additive insert.
 * The whole file is wrapped in a single transaction so a failure partway
 * through never leaves a half-applied state.
 *
 * Run with `npm run seed` (wired to `tsx scripts/seed.ts`).
 */
import { writeFileSync } from "node:fs";
import { resolve } from "node:path";
import catalogue from "../content/seed/catalogue";
import type { Product } from "../src/types/catalogue";
import { deterministicUuid } from "./lib/deterministic-uuid";

function sqlString(value: string | null | undefined): string {
  if (value == null) return "null";
  return `'${value.replace(/'/g, "''")}'`;
}

function sqlNumber(value: number | null | undefined): string {
  return value == null ? "null" : String(value);
}

function sqlBool(value: boolean): string {
  return value ? "true" : "false";
}

function sqlTimestamp(value: string | null | undefined): string {
  return value == null ? "null" : `'${value}'`;
}

function main() {
  const categoryIds = new Map(catalogue.categories.map((c) => [c.slug, deterministicUuid(`category:${c.slug}`)]));
  const stageIds = new Map(catalogue.stages.map((s) => [s.slug, deterministicUuid(`stage:${s.slug}`)]));
  const licenceIds = new Map(catalogue.licences.map((l) => [l.slug, deterministicUuid(`licence:${l.slug}`)]));
  // Keyed by the fixture's own `id` field (e.g. "framework-product-idea-assessor"), which
  // is what `Product.framework_id` references in content/seed/catalogue.ts — not the slug.
  const frameworkIds = new Map(catalogue.frameworks.map((f) => [f.id, deterministicUuid(`framework:${f.slug}`)]));

  const allProducts: Product[] = [...catalogue.products, ...catalogue.bundles];
  const productIds = new Map(allProducts.map((p) => [p.slug, deterministicUuid(`product:${p.slug}`)]));

  const lines: string[] = [
    "-- Generated by scripts/seed.ts from content/seed/catalogue.ts.",
    "-- Do not edit by hand — regenerate with `npm run seed`.",
    "-- Idempotent: safe to re-run against a database that already has some or all of this data.",
    "",
    "begin;",
    "",
    "-- it_categories",
  ];

  for (const c of catalogue.categories) {
    lines.push(
      `insert into public.it_categories (id, name, slug, description, display_order) values (${sqlString(
        categoryIds.get(c.slug)!,
      )}, ${sqlString(c.name)}, ${sqlString(c.slug)}, ${sqlString(c.description)}, ${sqlNumber(c.display_order)})` +
        " on conflict (id) do update set name = excluded.name, slug = excluded.slug, description = excluded.description, display_order = excluded.display_order;",
    );
  }

  lines.push("", "-- it_stages");
  for (const s of catalogue.stages) {
    lines.push(
      `insert into public.it_stages (id, name, slug, description, display_order) values (${sqlString(
        stageIds.get(s.slug)!,
      )}, ${sqlString(s.name)}, ${sqlString(s.slug)}, ${sqlString(s.description)}, ${sqlNumber(s.display_order)})` +
        " on conflict (id) do update set name = excluded.name, slug = excluded.slug, description = excluded.description, display_order = excluded.display_order, is_active = true;",
    );
  }

  // TODO: it_licences has columns (full_text, version, max_users, is_active)
  // that src/types/catalogue.ts's Licence type doesn't carry yet. full_text
  // and version are filled with honest placeholders below rather than
  // guessed real legal text — see /legal/licences, which states the same.
  lines.push("", "-- it_licences");
  for (const l of catalogue.licences) {
    lines.push(
      [
        "insert into public.it_licences (id, name, slug, summary, full_text, commercial_use_allowed, client_work_allowed, redistribution_allowed, version) values (",
        `  ${sqlString(licenceIds.get(l.slug)!)}, ${sqlString(l.name)}, ${sqlString(l.slug)}, ${sqlString(l.summary)},`,
        `  ${sqlString("Full licence text pending legal review — see /legal/licences.")},`,
        `  ${sqlBool(l.commercial_use_allowed)}, ${sqlBool(l.client_work_allowed)}, ${sqlBool(l.redistribution_allowed)}, ${sqlString("1.0")}`,
        ")",
        "on conflict (id) do update set name = excluded.name, slug = excluded.slug, summary = excluded.summary,",
        "  commercial_use_allowed = excluded.commercial_use_allowed, client_work_allowed = excluded.client_work_allowed,",
        "  redistribution_allowed = excluded.redistribution_allowed;",
      ].join("\n"),
    );
  }

  lines.push("", "-- it_frameworks");
  // Two passes: insert/update every framework with next_step_framework_id left untouched
  // first (a self-referencing FK can't point at a not-yet-inserted row on first seed), then
  // a second pass of UPDATE statements to fill in the ones that have a next-step link.
  for (const f of catalogue.frameworks) {
    const journeyStageId = f.journey_stage ? stageIds.get(f.journey_stage.slug) : undefined;
    lines.push(
      [
        "insert into public.it_frameworks (",
        "  id, status, name, slug, short_description, problem_statement, outcome_statement,",
        "  target_audience, when_to_use, when_not_to_use, method_summary, journey_stage_id,",
        "  priority_score, priority_rationale, source_strength, source_note, flagship,",
        "  display_order, seo_title, seo_description, published_at",
        ") values (",
        `  ${sqlString(frameworkIds.get(f.id)!)}, ${sqlString(f.status)}, ${sqlString(f.name)}, ${sqlString(f.slug)}, ${sqlString(f.short_description)}, ${sqlString(f.problem_statement)}, ${sqlString(f.outcome_statement)},`,
        `  ${sqlString(f.target_audience)}, ${sqlString(f.when_to_use)}, ${sqlString(f.when_not_to_use)}, ${sqlString(f.method_summary)}, ${journeyStageId ? sqlString(journeyStageId) : "null"},`,
        `  ${sqlNumber(f.priority_score)}, ${sqlString(f.priority_rationale)}, ${sqlString(f.source_strength)}, ${sqlString(f.source_note)}, ${sqlBool(f.flagship)},`,
        `  ${sqlNumber(f.display_order)}, ${sqlString(f.seo_title)}, ${sqlString(f.seo_description)}, ${sqlTimestamp(f.published_at)}`,
        ")",
        "on conflict (id) do update set status = excluded.status, name = excluded.name, slug = excluded.slug,",
        "  short_description = excluded.short_description, problem_statement = excluded.problem_statement,",
        "  outcome_statement = excluded.outcome_statement, target_audience = excluded.target_audience,",
        "  when_to_use = excluded.when_to_use, when_not_to_use = excluded.when_not_to_use,",
        "  method_summary = excluded.method_summary, journey_stage_id = excluded.journey_stage_id,",
        "  priority_score = excluded.priority_score, priority_rationale = excluded.priority_rationale,",
        "  source_strength = excluded.source_strength, source_note = excluded.source_note,",
        "  flagship = excluded.flagship, display_order = excluded.display_order, seo_title = excluded.seo_title,",
        "  seo_description = excluded.seo_description, published_at = excluded.published_at;",
      ].join("\n"),
    );
  }

  const frameworkIdBySlug = new Map(catalogue.frameworks.map((f) => [f.slug, frameworkIds.get(f.id)!]));
  lines.push("", "-- it_frameworks next-step links (second pass, see comment above)");
  for (const f of catalogue.frameworks) {
    const nextStepId = f.next_step_framework_slug ? frameworkIdBySlug.get(f.next_step_framework_slug) : undefined;
    lines.push(
      `update public.it_frameworks set next_step_framework_id = ${nextStepId ? sqlString(nextStepId) : "null"} where id = ${sqlString(frameworkIds.get(f.id)!)};`,
    );
  }

  // v9 §14.3.1: curated Collections layer above frameworks.
  const collectionIds = new Map(catalogue.collections.map((c) => [c.slug, deterministicUuid(`collection:${c.slug}`)]));

  lines.push("", "-- it_collections");
  for (const col of catalogue.collections) {
    lines.push(
      [
        "insert into public.it_collections (",
        "  id, name, slug, status, public_visibility, headline, short_description, display_order, is_core, seo_title, seo_description, published_at",
        ") values (",
        `  ${sqlString(collectionIds.get(col.slug)!)}, ${sqlString(col.name)}, ${sqlString(col.slug)}, ${sqlString(col.status)}, 'public', ${sqlString(col.headline)}, ${sqlString(col.short_description)}, ${sqlNumber(col.display_order)}, ${sqlBool(col.is_core)}, ${sqlString(col.seo_title)}, ${sqlString(col.seo_description)}, ${sqlTimestamp(col.published_at)}`,
        ")",
        "on conflict (id) do update set name = excluded.name, slug = excluded.slug, status = excluded.status,",
        "  public_visibility = excluded.public_visibility, headline = excluded.headline,",
        "  short_description = excluded.short_description, display_order = excluded.display_order,",
        "  is_core = excluded.is_core, seo_title = excluded.seo_title, seo_description = excluded.seo_description,",
        "  published_at = excluded.published_at;",
      ].join("\n"),
    );
  }

  // it_collection_frameworks has no natural single-column id to key an upsert on, and a
  // collection's membership/ordering can change entirely between runs — same "full replace"
  // reasoning as it_product_categories/it_product_stages below, applied per-collection.
  lines.push("", "-- it_collection_frameworks (full replace per collection this script manages)");
  for (const col of catalogue.collections) {
    const collectionId = collectionIds.get(col.slug)!;
    lines.push(`delete from public.it_collection_frameworks where collection_id = ${sqlString(collectionId)};`);
    for (const member of col.members) {
      const frameworkId = frameworkIdBySlug.get(member.framework_slug);
      if (!frameworkId) continue;
      lines.push(
        [
          "insert into public.it_collection_frameworks (collection_id, framework_id, step_order, step_label, transition_copy, is_required) values (",
          `  ${sqlString(collectionId)}, ${sqlString(frameworkId)}, ${sqlNumber(member.step_order)}, ${sqlString(member.step_label)}, ${sqlString(member.transition_copy)}, ${sqlBool(member.is_required)}`,
          ");",
        ].join("\n"),
      );
    }
  }

  lines.push("", "-- it_products");
  for (const p of allProducts) {
    const id = productIds.get(p.slug)!;
    const licenceId = p.licence ? licenceIds.get(p.licence.slug) : undefined;
    const frameworkId = p.framework_id ? frameworkIds.get(p.framework_id) : undefined;
    const schemaData = JSON.stringify({ placeholder: p.is_placeholder }).replace(/'/g, "''");
    lines.push(
      [
        "insert into public.it_products (",
        "  id, product_type, access_type, status, name, slug, short_description, full_description,",
        "  outcome_statement, target_audience, when_to_use, when_not_to_use,",
        "  completion_minutes_min, completion_minutes_max, skill_level, current_version,",
        "  price_minor, compare_at_price_minor, currency_code, licence_id, featured,",
        "  published_at, scheduled_for, seo_title, seo_description, schema_data,",
        "  framework_id, tool_key",
        ") values (",
        `  ${sqlString(id)}, ${sqlString(p.product_type)}, ${sqlString(p.access_type)}, ${sqlString(p.status)}, ${sqlString(p.name)}, ${sqlString(p.slug)}, ${sqlString(p.short_description)}, ${sqlString(p.full_description)},`,
        `  ${sqlString(p.outcome_statement)}, ${sqlString(p.target_audience)}, ${sqlString(p.when_to_use)}, ${sqlString(p.when_not_to_use)},`,
        `  ${sqlNumber(p.completion_minutes_min)}, ${sqlNumber(p.completion_minutes_max)}, ${sqlString(p.skill_level)}, ${sqlString(p.current_version)},`,
        `  ${sqlNumber(p.price_minor)}, ${sqlNumber(p.compare_at_price_minor)}, ${sqlString(p.currency_code)}, ${licenceId ? sqlString(licenceId) : "null"}, ${sqlBool(p.featured)},`,
        `  ${sqlTimestamp(p.published_at)}, ${sqlTimestamp(p.scheduled_for)}, ${sqlString(p.seo_title)}, ${sqlString(p.seo_description)}, '${schemaData}'::jsonb,`,
        `  ${frameworkId ? sqlString(frameworkId) : "null"}, ${sqlString(p.tool_key)}`,
        ")",
        "on conflict (id) do update set product_type = excluded.product_type, access_type = excluded.access_type,",
        "  status = excluded.status, name = excluded.name, slug = excluded.slug,",
        "  short_description = excluded.short_description, full_description = excluded.full_description,",
        "  outcome_statement = excluded.outcome_statement, target_audience = excluded.target_audience,",
        "  when_to_use = excluded.when_to_use, when_not_to_use = excluded.when_not_to_use,",
        "  completion_minutes_min = excluded.completion_minutes_min, completion_minutes_max = excluded.completion_minutes_max,",
        "  skill_level = excluded.skill_level, current_version = excluded.current_version,",
        "  price_minor = excluded.price_minor, compare_at_price_minor = excluded.compare_at_price_minor,",
        "  currency_code = excluded.currency_code, licence_id = excluded.licence_id, featured = excluded.featured,",
        "  published_at = excluded.published_at, scheduled_for = excluded.scheduled_for, seo_title = excluded.seo_title,",
        "  seo_description = excluded.seo_description, schema_data = excluded.schema_data,",
        "  framework_id = excluded.framework_id, tool_key = excluded.tool_key;",
      ].join("\n"),
    );
  }

  // it_product_categories / it_product_stages have no natural single-column id to key an
  // upsert on, and a product's category/stage set can shrink or change entirely between
  // runs (e.g. the v3 journey-stage remap left every product pointing at different stage
  // ids) — so these two sections delete every existing row for the products this script
  // manages first, making the insert that follows an authoritative full replace.
  const managedProductIds = allProducts.map((p) => sqlString(productIds.get(p.slug)!));

  lines.push(
    "",
    "-- it_product_categories (full replace for the products this script manages)",
    `delete from public.it_product_categories where product_id in (${managedProductIds.join(", ")});`,
  );
  for (const p of allProducts) {
    const id = productIds.get(p.slug)!;
    p.categories.forEach((c, index) => {
      const categoryId = categoryIds.get(c.slug);
      if (!categoryId) return;
      lines.push(
        `insert into public.it_product_categories (product_id, category_id, is_primary) values (${sqlString(id)}, ${sqlString(categoryId)}, ${sqlBool(index === 0)});`,
      );
    });
  }

  lines.push(
    "",
    "-- it_product_stages (full replace for the products this script manages)",
    `delete from public.it_product_stages where product_id in (${managedProductIds.join(", ")});`,
  );
  for (const p of allProducts) {
    const id = productIds.get(p.slug)!;
    p.stages.forEach((s, index) => {
      const stageId = stageIds.get(s.slug);
      if (!stageId) return;
      lines.push(
        `insert into public.it_product_stages (product_id, stage_id, is_primary) values (${sqlString(id)}, ${sqlString(stageId)}, ${sqlBool(index === 0)});`,
      );
    });
  }

  lines.push("", "commit;");

  const outputPath = resolve(process.cwd(), "supabase/seed.sql");
  writeFileSync(outputPath, lines.join("\n") + "\n", "utf8");
  console.log(
    `Wrote ${outputPath} (${allProducts.length} products, ${catalogue.frameworks.length} frameworks, ${catalogue.collections.length} collections, ${catalogue.categories.length} categories, ${catalogue.stages.length} stages, ${catalogue.licences.length} licences).`,
  );
}

main();
