/**
 * Reads content/seed/catalogue.ts (the single source of truth for local
 * fixture content) and writes supabase/seed.sql — plain SQL insert
 * statements matching spec §14's column names for it_categories, it_stages,
 * it_licences, it_products, it_product_categories and it_product_stages.
 * This keeps what the app renders locally (via FixtureCatalogueSource) and
 * what would get pushed to a real Supabase project in sync, with one file
 * as the source of truth rather than maintaining both by hand.
 *
 * Deliberately does NOT insert into it_product_versions, it_files or
 * it_bundle_items (not listed in the build plan's §8 scope for this
 * script) — those need real Storage-backed file rows and version records
 * that don't exist as fixture data in a form this script can safely turn
 * into SQL yet.
 *
 * Run with `npm run seed` (wired to `tsx scripts/seed.ts`).
 */
import { createHash } from "node:crypto";
import { writeFileSync } from "node:fs";
import { resolve } from "node:path";
import catalogue from "../content/seed/catalogue";
import type { Product } from "../src/types/catalogue";

/**
 * Fixture ids are human-readable slugs (e.g. "product-idea-snapshot"), not
 * valid Postgres uuids. This derives a stable, deterministic uuid-shaped
 * value from each slug (sha256 truncated into the 8-4-4-4-12 hex layout) so
 * re-running the script produces byte-identical output — a real seed
 * migration should be reproducible, not randomised per run.
 */
function deterministicUuid(seed: string): string {
  const hash = createHash("sha256").update(seed).digest("hex");
  return [hash.slice(0, 8), hash.slice(8, 12), hash.slice(12, 16), hash.slice(16, 20), hash.slice(20, 32)].join("-");
}

function sqlString(value: string | null | undefined): string {
  if (value == null) return "null";
  return `'${value.replace(/'/g, "''")}'`;
}

function sqlNumber(value: number | null | undefined): string {
  return value == null ? "null" : String(value);
}

function sqlBool(value: boolean): string {
  return value ? "true" : "false";
}

function sqlTimestamp(value: string | null | undefined): string {
  return value == null ? "null" : `'${value}'`;
}

function main() {
  const categoryIds = new Map(catalogue.categories.map((c) => [c.slug, deterministicUuid(`category:${c.slug}`)]));
  const stageIds = new Map(catalogue.stages.map((s) => [s.slug, deterministicUuid(`stage:${s.slug}`)]));
  const licenceIds = new Map(catalogue.licences.map((l) => [l.slug, deterministicUuid(`licence:${l.slug}`)]));

  const allProducts: Product[] = [...catalogue.products, ...catalogue.bundles];
  const productIds = new Map(allProducts.map((p) => [p.slug, deterministicUuid(`product:${p.slug}`)]));

  const lines: string[] = [
    "-- Generated by scripts/seed.ts from content/seed/catalogue.ts.",
    "-- Do not edit by hand — regenerate with `npm run seed`.",
    "",
    "-- it_categories",
  ];

  for (const c of catalogue.categories) {
    lines.push(
      `insert into public.it_categories (id, name, slug, description, display_order) values (${sqlString(
        categoryIds.get(c.slug)!,
      )}, ${sqlString(c.name)}, ${sqlString(c.slug)}, ${sqlString(c.description)}, ${sqlNumber(c.display_order)});`,
    );
  }

  lines.push("", "-- it_stages");
  for (const s of catalogue.stages) {
    lines.push(
      `insert into public.it_stages (id, name, slug, description, display_order) values (${sqlString(
        stageIds.get(s.slug)!,
      )}, ${sqlString(s.name)}, ${sqlString(s.slug)}, ${sqlString(s.description)}, ${sqlNumber(s.display_order)});`,
    );
  }

  // TODO: it_licences has columns (full_text, version, max_users, is_active)
  // that src/types/catalogue.ts's Licence type doesn't carry yet. full_text
  // and version are filled with honest placeholders below rather than
  // guessed real legal text — see /legal/licences, which states the same.
  lines.push("", "-- it_licences");
  for (const l of catalogue.licences) {
    lines.push(
      [
        "insert into public.it_licences (id, name, slug, summary, full_text, commercial_use_allowed, client_work_allowed, redistribution_allowed, version) values (",
        `  ${sqlString(licenceIds.get(l.slug)!)}, ${sqlString(l.name)}, ${sqlString(l.slug)}, ${sqlString(l.summary)},`,
        `  ${sqlString("Full licence text pending legal review — see /legal/licences.")},`,
        `  ${sqlBool(l.commercial_use_allowed)}, ${sqlBool(l.client_work_allowed)}, ${sqlBool(l.redistribution_allowed)}, ${sqlString("1.0")}`,
        ");",
      ].join("\n"),
    );
  }

  lines.push("", "-- it_products");
  for (const p of allProducts) {
    const id = productIds.get(p.slug)!;
    const licenceId = p.licence ? licenceIds.get(p.licence.slug) : undefined;
    const schemaData = JSON.stringify({ placeholder: p.is_placeholder }).replace(/'/g, "''");
    lines.push(
      [
        "insert into public.it_products (",
        "  id, product_type, access_type, status, name, slug, short_description, full_description,",
        "  outcome_statement, target_audience, when_to_use, when_not_to_use,",
        "  completion_minutes_min, completion_minutes_max, skill_level, current_version,",
        "  price_minor, compare_at_price_minor, currency_code, licence_id, featured,",
        "  published_at, scheduled_for, seo_title, seo_description, schema_data",
        ") values (",
        `  ${sqlString(id)}, ${sqlString(p.product_type)}, ${sqlString(p.access_type)}, ${sqlString(p.status)}, ${sqlString(p.name)}, ${sqlString(p.slug)}, ${sqlString(p.short_description)}, ${sqlString(p.full_description)},`,
        `  ${sqlString(p.outcome_statement)}, ${sqlString(p.target_audience)}, ${sqlString(p.when_to_use)}, ${sqlString(p.when_not_to_use)},`,
        `  ${sqlNumber(p.completion_minutes_min)}, ${sqlNumber(p.completion_minutes_max)}, ${sqlString(p.skill_level)}, ${sqlString(p.current_version)},`,
        `  ${sqlNumber(p.price_minor)}, ${sqlNumber(p.compare_at_price_minor)}, ${sqlString(p.currency_code)}, ${licenceId ? sqlString(licenceId) : "null"}, ${sqlBool(p.featured)},`,
        `  ${sqlTimestamp(p.published_at)}, ${sqlTimestamp(p.scheduled_for)}, ${sqlString(p.seo_title)}, ${sqlString(p.seo_description)}, '${schemaData}'::jsonb`,
        ");",
      ].join("\n"),
    );
  }

  lines.push("", "-- it_product_categories");
  for (const p of allProducts) {
    const id = productIds.get(p.slug)!;
    p.categories.forEach((c, index) => {
      const categoryId = categoryIds.get(c.slug);
      if (!categoryId) return;
      lines.push(
        `insert into public.it_product_categories (product_id, category_id, is_primary) values (${sqlString(id)}, ${sqlString(categoryId)}, ${sqlBool(index === 0)});`,
      );
    });
  }

  lines.push("", "-- it_product_stages");
  for (const p of allProducts) {
    const id = productIds.get(p.slug)!;
    p.stages.forEach((s, index) => {
      const stageId = stageIds.get(s.slug);
      if (!stageId) return;
      lines.push(
        `insert into public.it_product_stages (product_id, stage_id, is_primary) values (${sqlString(id)}, ${sqlString(stageId)}, ${sqlBool(index === 0)});`,
      );
    });
  }

  const outputPath = resolve(process.cwd(), "supabase/seed.sql");
  writeFileSync(outputPath, lines.join("\n") + "\n", "utf8");
  console.log(`Wrote ${outputPath} (${allProducts.length} products, ${catalogue.categories.length} categories, ${catalogue.stages.length} stages, ${catalogue.licences.length} licences).`);
}

main();
